### ISSUE TITLE
Text is cut off no matter how high or low it's rasied in mod settings

### ISSUE THREAD

**Issue by MagicOriole** [mclemente/healthEstimate#103]
![image](https://user-images.githubusercontent.com/96490347/193424553-31521988-a19e-4309-90b8-eba9727bdddc.png)

**Comment by MagicOriole** [comment]
Confirmed creature size is irrelevant:

![image](https://user-images.githubusercontent.com/96490347/193424606-41a81199-a558-416c-9f04-eaa7bda04924.png)

**Comment by weepingminotaur** [comment]
Can verify this issue on Foundry v10. Text is cut off no matter where it's positioned, the size, or the size of the creature.

**Comment by mclemente** [comment]
Sorry, I forgot to push the fix. Try updating and check out if the text is still cropped.

**Comment by MagicOriole** [comment]
Fixed. Thank you mclemente! Love the Alexstrasza profile pic too haha

**Comment by MagicOriole** [comment]
Unfortunately it started happening again.

**Comment by mclemente** [comment]
What settings are you using? It doesn't happen on the default settings.
![image](https://user-images.githubusercontent.com/5288872/196821458-173d09ec-46a0-417c-b9f2-f244afc56608.png)
