### ISSUE TITLE
FoundryVTT V10 noting critical error in console for [healthEstimate]

### ISSUE THREAD

**Issue by drszxn** [mclemente/healthEstimate#104]
[healthEstimate] Metadata validation failed for module "healthEstimate": The file "lib/color-picker.min.js" included by module healthEstimate does not exist
#logPackageWarnings @ setup.js:141

![image](https://user-images.githubusercontent.com/11803128/195093527-c96227e1-675f-4e4d-8952-459f57dbf560.png)

==========

![image](https://user-images.githubusercontent.com/11803128/195093857-969d2368-bddb-407b-abf0-8503265f47c9.png)

![image](https://user-images.githubusercontent.com/11803128/195093960-54d2e337-cfbd-4b20-9069-413d37625556.png)

![image](https://user-images.githubusercontent.com/11803128/195094256-bdf4b4ee-2a83-402d-a765-d070e591e702.png)

**Comment by drszxn** [comment]
and just like that, it stopped... :-/

**Comment by mclemente** [comment]
You updated from Foundry V9 to V10 right before this, right? The module.json of this module for V9 had a missing file listed, which didn't throw errors on V9, but V10's validation is strictier.
