### ISSUE TITLE
New Feature: Unconcious when you have 1 wound beyond your total.

### ISSUE THREAD

**Issue by valdier1** [mclemente/healthEstimate#105]
In systems like Savage Worlds, you have 2 types of characters:
Extras (1 wound and they are out)
Wild Cards (can take 3 wounds then 1 more and they are out)

Would there be a way to support this? Or, even better, only mark unconscious state based on a specific status effect? If "Incapacitated", status then show "unconscious: title" if "dead" status show dead. These could be user configurable fields perhaps?

**Comment by mclemente** [comment]
> Extras (1 wound and they are out)
> Wild Cards (can take 3 wounds then 1 more and they are out)
>Would there be a way to support this? 

Version 29.6 should improve on these.

> Or, even better, only mark unconscious state based on a specific status effect? If "Incapacitated", status then show "unconscious: title" if "dead" status show dead. These could be user configurable fields perhaps?

Dead status, e.g. the big skull marker that you add through the combat tracker, has also been added.

Incapacitated, e.g. the skull effect, can be added, but will take a bit longer. I'm not sure about making it configurable, though.

**Comment by mclemente** [comment]
Check the new version out. I suggest toggling the "NPCs Die Immediately" setting on if you intend for your Extras and 4/3 Wild Cards to be dead.
