### ISSUE TITLE
Module uses default PIXI font instead of CONFIG.canvasTextStyle

### ISSUE THREAD

**Issue by n0q** [mclemente/healthEstimate#111]
Your module is terrific, but it uses whatever font PIXI feels like serving up. This is okay, but it clashes with any system which changes the canvas font.
![fontclash](https://user-images.githubusercontent.com/7948363/205221420-01adb6d4-1852-44ef-ad9c-ad91ac4899fb.jpg)

Would it be possible to default to using `CONFIG.canvasTextStyle` and then merging any user changes? I'm willing to write the pr myself.

**Comment by mclemente** [comment]
The thought never crossed my mind since systems I play use the default font. That's an awesome contribution, thank you!
