### ISSUE TITLE
frozen scene bug (after migrating v9 to v10)

### ISSUE THREAD

**Issue by Fridan99** [mclemente/healthEstimate#115]
Foundry vtt 10.291

dnd5e System 2.0.3

Health Estimate 29.5.7

Other modules activated: NO

**Description of the problem**.  After migrating the world from v9 to v10, there seems to be a strange problem happening with the Health Estimate. When activating the module (no other modules active), the hp estimate message over the token in the canvas does not appear above the tokens, and the scene-canvas freezes.

Img console log
![1](https://user-images.githubusercontent.com/86131373/209852779-6dfb6ba7-18ab-439a-bcd2-0fcd00635c7d.jpg)

----------------------------------------------------------------
**Test: in a new test world**

I cannot replicate the problem. It seems to work. It seems to be due to some conflict with migration.

**Comment by mclemente** [comment]
Just to be sure, does this happen to the scene without Health Estimate activated too? The first error is thrown by the dnd5e system trying to render the HP bar, and the second is cut short, but it's probably the same source.

**Comment by Fridan99** [comment]
No, when I deactivate Health Estimate the bug disappears in that scene (then i can open sheets, move tokens... again). I have isolated the problem, because I have deactivated/activated one by one the modules.

It is true that in a new test world with another scene the bug does not occur. 
I will try during the day in another scene of the migrated world.

**Comment by mclemente** [comment]
If you create a brand new scene, does this error happens?

Also, your log shows 3 errors, is the third one just like these two?

**Comment by Fridan99** [comment]
I created a new scene, and the error manifested itself when dragging a token (actor) onto the canvas. If I don't do this, the error does not manifest itself as far as I can see. 

Console error (other scene, and new scene.... with actors in the canvas)
![1](https://user-images.githubusercontent.com/86131373/210187815-1ba73d3b-d94e-446a-b38d-0360587a35d6.jpg)

**Comment by mclemente** [comment]
Hm, can you export that scene and upload it here? Or even zip that world's folder and upload it here? I can't reproduce this with my world.

**Comment by Fridan99** [comment]
> Hm, can you export that scene and upload it here? Or even zip that world's folder and upload it here? I can't reproduce this with my world.

Secene and actor.zip (via Wetransfer link)

https://we.tl/t-IXomlMRYcK

**Comment by mclemente** [comment]
I couldn't reproduce the error.
![image](https://user-images.githubusercontent.com/5288872/211436751-8a7ae433-7408-4fa0-9450-300c30fc5b4c.png)

By the way, does this happen only with the module enabled? As in, does running with it disabled works fine?

**Comment by Fridan99** [comment]
Yes, it is with the module activated that the problem is reproduced (without the module, the foundry runs well). I will try to migrate again from another pc, from v9 to v10, this time deleting the Healt Estimate, and doing a clean install. 

In case it comes back, I can give you access to my world, or pass you a copy of my world.

**Comment by Fridan99** [comment]
I put the bug on discord, and I got this reply... 

dev7355608 — today at 21:51
I came across this error recently in another module. I briefly looked at Health Estimate's code. Maybe the font size is not 0 but invalid. Try to reset the font size and reload
game.settings.set("healthEstimate", "core.menuSettings.fontSize", "x-large")

**Comment by Fridan99** [comment]
i put that command in the console and the bug was gone.... but the font of Health Estimate is too big :P
