### ISSUE TITLE
Error when updating Temp HP from macro

### ISSUE THREAD

**Issue by nschoenwald** [mclemente/healthEstimate#116]
I am using the following macro to update my players' temp HP for the inspiring leader feat:
`for(const user of game.users) await user.character?.applyTempHP(7);
`
This results in an error and no messages are generated by healthEstimate:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/72390280/211191735-67ecec17-77da-4d6f-8d89-12fdcf0e524e.png">

**Comment by mclemente** [comment]
That's [Health Monitor](https://github.com/jessev14/health-monitor), not Health Estimate.

**Comment by nschoenwald** [comment]
Oh my, I'm sorry! Please disregard and delete this issue, then.
