### ISSUE TITLE
Non-smooth gradient applies the wrong color

### ISSUE THREAD

**Issue by digitalpacman** [mclemente/healthEstimate#117]
Essentially if you take smooth gradient off, it applies one color ahead in the progress.  

Steps to reproduce
Create a monster with 100 HP
Open Health Estimate settings
Set to 4 stages.  "A, B, C, D"
Save Changes
Open health estimate settings
uncheck smooth gradiant. You should see 4 bars - red, orange, light green, green
Hit Save changes
set monster hp to 48 - the text will be light green, not orange. Red will never be used until dead.

**Comment by digitalpacman** [comment]
If you add smooth gradient back on, at 1 hp, the text will change to red. - correctly

**Comment by mclemente** [comment]
Thanks for the steps. This is fixed on version 29.5.8.
