### ISSUE TITLE
Bug - Cyberpunk Red Core system estimate not synced

### ISSUE THREAD

**Issue by diwako** [mclemente/healthEstimate#119]
The module has support for the system, it works very well as a GM. It however does not work for a player, the estimate will always say "Not Wounded".

As example:

GM view
![image](https://user-images.githubusercontent.com/8259498/212734919-14823281-3d70-4abe-897b-4fbc1adc6000.png)

Player view
![image](https://user-images.githubusercontent.com/8259498/212734973-ea31ef88-00f4-4aaf-bdea-9f52c972e248.png)

**Comment by mclemente** [comment]
Hm, this issue only happens when the module setting "Use Wound States" is on.
For whatever reason, CPR's wounds aren't being calculated to players the same way to GMs, unless they control the character (e.g it shows correctly to player-owned characters, but not to NPCs).
I'll look for a solution with CPR devs. In the meantime, disable the module's setting and things should show up the same for both of you.

**Comment by mclemente** [comment]
While this isn't fixed on the system's side (https://gitlab.com/cyberpunk-red-team/fvtt-cyberpunk-red-core/-/issues/680), I'll remove the setting for the time being to avoid more people running into this issue.

**Comment by diwako** [comment]
The temporary fix i am using since the beginning was just use the custom stages
`Mortally Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Healthy`

it is.. weird okay, it mostly works... The players know the current and max hp of the other tokens at least.

**Comment by MrChessur** [comment]
Just started checking up on this. This is my temporary fix, and it is completely accurate But a lot more tedious looking...

>Mortally Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Seriously Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Lightly Wounded, Preem

**Comment by mclemente** [comment]
I believe the new way to setup estimations on version 30 fixed this issue. May I consider this solved?

**Comment by diwako** [comment]
I do have a session tomorrow, which allows me to check. I will reply after the session then

**Comment by diwako** [comment]
just updated and checked, module is not working anymore
This error is in the console when loading into the world

```log
TypeError: Error thrown in hooked function '' for hook 'setup'. providers.cyberpunkRedEstimationProvider is not a constructor
[Detected 1 package: healthEstimate]
    at eval (eval at prepareSystemSpecifics (logic.js:48:10), <anonymous>:1:1)
    at HealthEstimate.prepareSystemSpecifics (logic.js:48:10)
    at HealthEstimate.setup (logic.js:13:34)
    at Object.fn (healthEstimate.js:12:22)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Game.setupGame (foundry.js:7913:11)
    at Game._initializeGameView (foundry.js:8999:16)
    at Game._initializeView (foundry.js:8975:21)
    at Game.initialize (foundry.js:7825:16)
 ```

**Comment by mclemente** [comment]
Oof. Update the module and it should work now.

**Comment by diwako** [comment]
thank you, unfortunately I am already in bed, will check the changes tomorrow morning

**Comment by diwako** [comment]
Can confirm working now. one minor issue tho. The system haw now container characters, those have no hp. Health estimate errors out on those
```
HealthMonitor.js:20 Health Estimate | Error on function getCharacters(). Token Name: "Sid's Vendit Shop". Type: "container". TypeError: Cannot read properties of undefined (reading 'hp')
    at HealthEstimate.fraction [as fractionFormula] (EstimationProvider.js:370:46)
    at HealthEstimate.getFraction (logic.js:203:36)
    at getCharacters (HealthMonitor.js:15:48)
    at Object.fn (healthEstimate.js:28:2)
    at #call (foundry.js:724:20)
    at Hooks.call (foundry.js:706:38)
    at Canvas.draw (foundry.js:23693:13)
    at async Scene.view (foundry.js:20901:7)
```
