### ISSUE TITLE
Support for Shadow of the Demon Lord

### ISSUE THREAD

**Issue by zaksquatch** [mclemente/healthEstimate#121]
Hello! I've used this module a bunch with other systems, but can understand why it doesn't inherently work out of the box for Shadow of the Demon Lord.

SotDL tracks "Damage" instead of Health, meaning a character that is healthy has a value of 0 and a character that is dead is one who's damage is equal to their max health.

Unfortunately the fractions don't seem to work in a way to allow that. 

Thanks for everything!

**Comment by mclemente** [comment]
Are you sure? It should work with this:
Hit Points Attribute Data Path: `actor.system.characteristics.health`
Fraction Equation set to the 2nd option, `(Max - Cur)/Max`.

**Comment by zaksquatch** [comment]
You could be right. Maybe it was just a matter of not updating properly, in which case I am dreadfully sorry. Let me give it a try.

**Comment by zaksquatch** [comment]
Well, thanks for the quick assist and pointing out my error. Thank you for your time!
