### ISSUE TITLE
Add setting for temporary hp path

### ISSUE THREAD

**Issue by Arkandos** [mclemente/healthEstimate#124]
Currently, there is no way to set the path for temporary hp, and I don't know what the default path is.

**Comment by mclemente** [comment]
What system are you on? Temp HP generally is set as part of the hp data path, since they deal with the same thing, so that's why it was never needed.

**Comment by Arkandos** [comment]
Custom System Builder! I had to point the hp path to an attribute bar or it wouldn't work.

Allowing temp hp path to be a separate setting would make it work with those systems that have 2 sets of hp, as others have mentioned.

**Comment by Arkandos** [comment]
Some further testing shows that it doesn't quite work with Custom System Builder, the health estimate resets overtime to Uninjured. Changing hp shows the correct estimate for a while again.

**Comment by mclemente** [comment]
Hey, update and check the new setting, it should solve this issue.

**Comment by Arkandos** [comment]
Updated to the new version, the module no longer works at all and gives the following error when hovering a token: 
![image](https://user-images.githubusercontent.com/5114247/219978581-825b8e8d-d42c-4d66-aee3-3040d26ec3ae.png)

**Comment by mclemente** [comment]
Should work now. I also noticed it shouldn't target the `props` data path, but `attributeBar` instead.

**Comment by Arkandos** [comment]
Latest update fixed it! Thanks
