### ISSUE TITLE
Bug: Position is different depending on Scene Grid Size

### ISSUE THREAD

**Issue by yjeroen** [mclemente/healthEstimate#128]
This is a problem if you use multiple scenes with different grid sizes.

Example
![image](https://user-images.githubusercontent.com/1303988/220767748-f8fc8968-eac2-4417-9af7-09616bbfe010.png)

![image](https://user-images.githubusercontent.com/1303988/220767826-b4a724fb-fb3f-4c84-9403-19fca606eca5.png)

![image](https://user-images.githubusercontent.com/1303988/220767990-58d38689-72af-47e7-b854-7188da6a1821.png)

**Comment by mclemente** [comment]
Should be fixed now on the latest version.
