### ISSUE TITLE
No Longer working on Pf2e

### ISSUE THREAD

**Issue by WaterpoloBlock** [mclemente/healthEstimate#140]
This is the only module I have enabled.

Health estimates will not show regardless of the setting changes I make.
Was working fine last week

Foundry version: 291
Pathfinder 2e: 4.9.3

This is the error message I get:
foundry.js:727 Foundry VTT | Error thrown in hooked function '' for hook 'refreshToken'
#call @ foundry.js:727
callAll @ foundry.js:681
refresh @ foundry.js:25225
(anonymous) @ logic.js:34
forEach @ commons.js:3265
canvasReady @ logic.js:34
(anonymous) @ healthEstimate.js:26
#call @ foundry.js:724
call @ foundry.js:706
draw @ foundry.js:23693
await in draw (async)
view @ foundry.js:20901
initializeCanvas @ foundry.js:8095
await in initializeCanvas (async)
setupGame @ foundry.js:7929
await in setupGame (async)
_initializeGameView @ foundry.js:8999
_initializeView @ foundry.js:8975
initialize @ foundry.js:7825
await in initialize (async)
window.addEventListener.once @ foundry.js:79693
foundry.js:747 TypeError: Error thrown in hooked function '' for hook 'refreshToken'. game.healthEstimate.breakOverlayRender is not a function
    at HealthEstimate._handleOverlay (logic.js:74:27)
    at Object.fn (logic.js:29:9)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at TokenPF2e.refresh (foundry.js:25225:11)
    at logic.js:34:76
    at EmbeddedCollection.forEach (commons.js:3265:9)
    at HealthEstimate.canvasReady (logic.js:34:44)
    at Object.fn (healthEstimate.js:26:22)
    at #call (foundry.js:724:20)

**Comment by mclemente** [comment]
It seems a change I've pushed is behaving weirdly. I've pushed a fix on v29.10, so update and it should be fixed.
Thank you for the report.

**Comment by WaterpoloBlock** [comment]
I can confirm it now works again.

Thank you.
