### ISSUE TITLE
bug - rounding error at <1% hp?

### ISSUE THREAD

**Issue by dharkus5000** [mclemente/healthEstimate#144]
with creatures with >200hp i think, when they have 1hp, they're marked as dead, i think it's likely rounding down to 0%, as it'd be like <0.49% hp

**Comment by mclemente** [comment]
>i think it's likely rounding down to 0%

Technically yes, it truncates to the first two decimals, so 0.009 (0.9%) becomes 0.00. I will add a check for when the percentage is smaller than 1% but not actually 0, and will move the truncation later.

**Comment by mclemente** [comment]
Should be fixed on the latest release.
