### ISSUE TITLE
Issue with system "Knight"

### ISSUE THREAD

**Issue by Zakarik** [mclemente/healthEstimate#145]
Hello, I am the creator of the Knight system on Foundry. I have been told about a compatibility problem between my system and your module.

I have searched a bit and the options of your module do not even appear in my tests, and I find myself with several errors that appear in your code.

I attach screenshots of the console errors.

Could you tell me what this is about? Can we see together to correct the problem ? I'm on the Foundry Discord under the nickname "Zakarik" if you want to contact me.

Oh and I'm French speaking, but I understand more or less English and I use a translator, so it's not a problem to communicate in writing !

![image](https://user-images.githubusercontent.com/8583530/230726189-51caba07-95bd-4d5b-9327-551d6bd4174e.png)

**Comment by mclemente** [comment]
It isn't a specific bug with your system, it's an issue with the subclass.

I already fixed it. Thanks for reporting it!
