### ISSUE TITLE
Issue: "Output Estimate to Chat" and "Hide Names" produces code instead of "Unknown Entity Name"; plus a few other issues

### ISSUE THREAD

**Issue by King-Wedgie** [mclemente/healthEstimate#146]
![image](https://user-images.githubusercontent.com/73143074/230788874-4bd24a65-e24e-4b52-8faa-404b2d0e81a4.png)
**Foundry VTT** _v10.291_
**Pathfinder 2nd Edition** _4.10.4_
**Health Estimate** _30.3_
All other modules (except for **Find the Culprit**) disabled for debugging 

1) (major issue) Title. Changing "Unknown Entity Name" doesn't produce anything different.
2) (minor issue) Chat estimate appears before the system's damage message.
3) (moderate issue) Chat estimate displays "Dead" tokens as "Unconcious"
~4) (lesser issue) "Death Marker" icon doesn't appear on out-of-combat tokens.~ PF2E system issue
5) (lesser issue) "{setting} setting" twice in the token config.

No errors in the console log.

**Comment by mclemente** [comment]
Fixed everything, except number 2, because I can't control when the message's processing will finish.

Sorry for your troubles and thanks for the report.

**Comment by King-Wedgie** [comment]
"except number 2" Figured that's what was happening there, but thought I'd post just in case.

Thanks, cool work.
