### ISSUE TITLE
Issue: Chat Estimate desyncs when multiple tokens tied to the same Represented Actor are in a scene together

### ISSUE THREAD

**Issue by King-Wedgie** [mclemente/healthEstimate#147]
Sorry for the return, but it looks like 30.4 has introduced a new issue.

**Foundry VTT** _v10.291_
**Pathfinder 2nd Edition** _4.10.4_
**Health Estimate** _30.4_
All other modules (except for Find the Culprit) disabled for debugging

Issue: Title. When multiple tokens to a single Represented Actor are in a scene (eg. a bunch of Giant Rats on a scene, pulled from a single Giant Rat from the Actors tab), the chat estimate won't update until _every_ token of that actor on that scene has some kind of HP change applied; and then, it only updates the first token that had a change, and won't update again unless you continue the sequential chain (eg. 1-2-3-1-2-3) or update each one again, resetting the chain. 

The bug only persists for the same actors on one scene (eg. a group of Giant Rats on Scene 1 won't chain with a group of Giant Rats on Scene 2). Multiple groups of multiple actor types on a scene remain as separate chains (eg. a group of Rats will only update within their group, and a group of Kobolds will only update with theirs).

No errors in the console log; everything else seems to be working fine.

**Comment by mclemente** [comment]
I don't think it was caused by 30.4, but it was definitely bugged.
