### ISSUE TITLE
Option to display always

### ISSUE THREAD

**Issue by vexofp** [mclemente/healthEstimate#15]
It would be nice if there was an option to display the health estimate always, instead of only on hover. This would be particularly useful for in-person play, when it may not be convenient for players to mouse around a shared display.

**Comment by mclemente** [comment]
I don't think it's possible currently, unfortunately.
The overlay binds to a token when it's shown, so it only works on one token at a time. So even if it wasn't hover-only, it would disappear as soon as you hover over another token.

**Comment by mclemente** [comment]
Update: unfortunately, this isn't feasible with Health Estimate. https://discord.com/channels/170995199584108546/596076404618166434/863425753064144946
