### ISSUE TITLE
Custom tables not working; "Reset to Default" not working

### ISSUE THREAD

**Issue by King-Wedgie** [mclemente/healthEstimate#154]
**Foundry VTT** v10.291
**Pathfinder 2nd Edition** v4.10.4
**Health Estimate** v 30.6.1
_All other modules disabled for debugging_

1) Specifically for PF2E (haven't tested other systems), Vehicles and Hazards are using the Default estimate table instead of the included custom table:
![image](https://user-images.githubusercontent.com/73143074/232253258-06c672d8-1e60-4d2c-935d-df7db22345e7.png)

2) [Reset Defaults] button in all three Settings menus does nothing except throw an error (text is for Estimation Settings):
[HealthEstimateSettings.js:135:4](http://localhost:30000/modules/healthEstimate/module/HealthEstimateSettings.js)
Uncaught (in promise) ReferenceError: resetToDefault is not defined 
    activateListeners http://localhost:30000/modules/healthEstimate/module/HealthEstimateSettings.js:135
    jQuery 8
        dispatch
        handle
        add
        Ee
        each
        each
        Ee
        on
    activateListeners http://localhost:30000/modules/healthEstimate/module/HealthEstimateSettings.js:134
    _render http://localhost:30000/scripts/foundry.js:5138
    _render http://localhost:30000/scripts/foundry.js:5822
    render http://localhost:30000/scripts/foundry.js:5067
    _onClickSubmenu http://localhost:30000/scripts/foundry.js:71944
    jQuery 2
        dispatch
        handle
    activateListeners http://localhost:30000/modules/healthEstimate/module/HealthEstimateSettings.js:139
    jQuery 8
        dispatch
        handle
        (Async: EventListener.handleEvent)
    add
        Ee
        each
        each
        Ee
        on
    activateListeners http://localhost:30000/modules/healthEstimate/module/HealthEstimateSettings.js:134
    _render http://localhost:30000/scripts/foundry.js:5138
    AsyncFunctionNext self-hosted:810
    (Async: async)
    _render http://localhost:30000/scripts/foundry.js:5822
    render http://localhost:30000/scripts/foundry.js:5067
    _onClickSubmenu http://localhost:30000/scripts/foundry.js:71944
    _onClickSubmenu self-hosted:1359
    jQuery 2
        dispatch
        handle

**Comment by mclemente** [comment]
These should be fixed on the latest version now.

**Comment by King-Wedgie** [comment]
Can confirm it's all fixed now. Thanks!

**Comment by mclemente** [comment]
I missed two other calls to reset, sorry about that. Next version will have those fixed too.
