### ISSUE TITLE
When Show Only on Combat is enabled, players need to refresh to see the change.

### ISSUE THREAD

**Issue by WaterpoloBlock** [mclemente/healthEstimate#158]
**Describe the bug**
With "Show Only on Combat" is enabled, and "Always Show Estimates" is disabled. 

After initiative has been rolled and I start the encounter. I will be able to see the health estimates appear over Npc/pcs. However, the players will not. For them to see it, it will require them to refresh the screen. 

If I end the encounter and start a new one, on the same scene. The players will still need to do refresh there screen to see the health estimates. 

I have tested this on: Chrome, Firefox, Brave, all in there private browsers too. The issue tracks. 

**To Reproduce**
1. Go to Configure settings and make sure "Always Show Estimates" is disabled and "Show Only on Combat" is enabled.
2. Be logged in as a GM and have a test account with only player rights.
3. Select the number of tokens on the map and have them roll initiative and start the encounter.
4. Change to the player account and see that the health estimates aren't being shown.
5. Refresh the screen as the player account, health estimates will be shown.

**Expected behavior**
For the Health Estimates to be shown when combat starts without the players needing to do a refresh.

**Screenshots**
Could only find 1 warning while logged in as the player, but always shows up with "Always Show Estimates." So could be a red herring. 

![image](https://user-images.githubusercontent.com/73310678/232323354-5fa1a1f0-3e43-440c-987e-7027e6568107.png)

**Game Specifics (please complete the following information):**
 - Game System and version: [Pathfinder 2e: 4.10.4
 - Version [291]
 - Using Forge Vtt
 - 3 Modules Active (Health Estimate, Pathfinder 2e: Abomination Vaults, The Forge)

**Additional context**
Only work around I have found is if I have "Always Show Estimates" is enabled. While not what I want to happen. Could be worse.

**Comment by mclemente** [comment]
Should be fixed now.
