### ISSUE TITLE
Outputting to chat multiple times

### ISSUE THREAD

**Issue by thejoester** [mclemente/healthEstimate#160]
Health Estimate v30.8.1
FVTT v10.291

So suddenly the addon is outputting to chat multiple times when an NPC takes damage and changes conditions. It seems to be "saying" the new status once for every person connected to the game, so instead of just sending to chat as GM it sends as each player too. 

![image](https://user-images.githubusercontent.com/7744795/233259579-d3cb2b1e-3237-4435-b01e-a13219a1c133.png)

**Comment by thejoester** [comment]
This is still happening even after the update

**Comment by mclemente** [comment]
Just to be sure, you had the setting disabled and then re-enabled it to test? As in, if you change the setting and reload the game, it wont happen. Because it's the only way that still happened.

**Comment by mclemente** [comment]
This should be completely fixed now.
