### ISSUE TITLE
Chat Output not working no matter what

### ISSUE THREAD

**Issue by TheTenk** [mclemente/healthEstimate#168]
for a short period I was able to make it work by disabling it, refreshing and re-enabling it, but now not even that jury-rig works.

**Comment by mclemente** [comment]
What system are you on? Any errors on the console?

**Comment by TheTenk** [comment]
Pathfinder 2nd Edition. I can't say I'm very proficient in spotting them,
but at least from what I can see I don't spawn any errors when i modify the
health (the estimate above the token updates just fine).
