### ISSUE TITLE
Cast Temp HP as a number before adding it to base HP

### ISSUE THREAD

**Issue by CeaneC** [mclemente/healthEstimate#17]
Not sure if this affects other systems, but it affects dnd5e at the very least. Because Temp HP is stored as a string (for some reason), when you try and add Temp HP to base HP here:
https://github.com/mclemente/healthEstimate/blob/0b06eb74c1b5b4b2730c14882c688c308142867d/module/systems/dnd5e.js#L18
It concatenates them as a string, instead of adding the numbers together. So a character with 16/32 base HP and 1 temp HP will read as having 116/32 HP and show as Healthy instead of  Injured.

A quick fix for this would be to format it like so:
```js
	return Math.min((+temp + +hp.value) / hp.max, 1);
```
This could work too, though I haven't tried it
https://github.com/mclemente/healthEstimate/blob/0b06eb74c1b5b4b2730c14882c688c308142867d/module/systems/dnd5e.js#L16
```js
	temp = +hp.temp;
```

**Comment by mclemente** [comment]
Is this on Foundry 0.7.9? Because I'm on 0.8 and hp.temp is an int.

**Comment by CeaneC** [comment]
Apologies, it looks like the issue is with the character sheet I'm using. When I switch to the D&D 5e sheet all is fine.
