### ISSUE TITLE
Low Priority - I saw this error but I don't think it's a problem. 

### ISSUE THREAD

**Issue by friction1** [mclemente/healthEstimate#173]
**Describe the bug**
I just saw this error and thought it might be helpful to share

**To Reproduce**
not sure

**Expected behavior**
I just saw this error and thought it might be helpful to share

**Screenshots**

**Game Specifics (please complete the following information):**
 - Game System and version: dnd5e 2.2.1
 - Version v11 build 302

**Additional context**
<img width="930" alt="Screenshot 2023-06-20 at 10 23 20 PM" src="https://github.com/mclemente/healthEstimate/assets/11384891/1b08d587-9d93-4dcf-94bf-897a576b8f75">

**Comment by AshnakAGQ** [comment]
This happened to me because I had a vehicle in the scene with undefined health that the party owned. Once I added health to it the error went away.
![image](https://github.com/mclemente/healthEstimate/assets/23924004/6775735c-2ce9-4e23-9d92-2956adcf032b)
