### ISSUE TITLE
Doesn't work on TheWitcherTRPG

### ISSUE THREAD

**Issue by DKtric3L** [mclemente/healthEstimate#180]
Does not pull up the value of the system's HP, although everything is indicated correctly. This problem has already arisen before, and I wrote to the developer's github in the same way, to which I received an answer that this is really a bug.
I play on Anthony Monette's TheWitcherTRPG system. Stat hp there is derivedStats.hp
The rest of the addon works fine with it, when this one does not see it.
I tried different variations -
Specified in the system files - WITCHER.Actor.DerStat.HP
With different attributes - derivedStats.hp.max/label/value
Tried to combine them. All to no avail.

1. Go to 'healthEstimate addon settings'
2. Click on 'Attribute Path'
3. Try to type System's DerivedStat'
4. See nothing

Screenshots
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/a1dab63c-3e7f-40fa-a3e3-b5ef8a50cc69)
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/6baea241-e0af-4043-b61b-731012b85102)
Token attributes 
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/717af396-21da-446f-922a-7805416edee1)

Game Specifics:
 - TheWitcherTRPG 0.96
 - FoundryVTT v11.304

**Comment by mclemente** [comment]
That is not the correct path, `actor` isn't optional, input `actor.derivedStats.hp`.

**Comment by DKtric3L** [comment]
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/4a16e1b4-21d0-4a57-bda0-7996e9d660b2)

**Comment by mclemente** [comment]
My bad, try `actor.system.derivedStats.hp` instead.

**Comment by DKtric3L** [comment]
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/71b903e3-b7c4-423e-9419-296a6618ce43)
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/5b94bf6f-b10c-4679-9495-c2005468276d)
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/de42707c-f17d-437d-a628-badca1fce8d7)
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/bdd63d68-9876-47a3-b10a-2f650237d3af)

**Comment by mclemente** [comment]
I meant "system" literally, not the system's name.

**Comment by DKtric3L** [comment]
well, as you see, i tried on the first screenshot.

**Comment by DKtric3L** [comment]
and I don't forget to reboot the system just in case after changes.

**Comment by DKtric3L** [comment]
and this happens even with disabled addons

**Comment by mclemente** [comment]
It should've worked. Does the token has HP set? Otherwise the estimates won't show up.
Not the max HP modified by BODY, but the value on the right side of the side. Somehow setting the value to 0 also changes the max to 0.

**Comment by DKtric3L** [comment]
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/b633aad6-d766-46b0-8617-5fac0fbc650a)
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/0f4a4a1a-690a-41c0-9735-f1ce0f78cc3c)
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/cbb7d16d-8d9e-406c-b97b-fd65d7bea305)
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/60b2e62d-d586-4972-8d7f-c0dbc1c68247)

**Comment by DKtric3L** [comment]
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/aa87b8b5-e239-49e3-b751-9fa5d897965c)

**Comment by mclemente** [comment]
Are there any errors on the console (F12) related to Health Estimate?

**Comment by DKtric3L** [comment]
where should I look in the console to check?

**Comment by DKtric3L** [comment]
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/fbca5ef9-5d6e-4fac-bf7e-c33a0e7055bd)

**Comment by DKtric3L** [comment]
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/ce3c3a38-ec24-40fb-ab94-c25e42f4bcd1)

**Comment by mclemente** [comment]
You got it right on the first image, it's the console at the bottom (or the console tab at the top).
Just to be sure, those are after you hovered over the token, right? It should be showing errors if it wasn't calculated properly.

**Comment by DKtric3L** [comment]
So i hovered token, no console changes
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/a149242f-41f9-42e1-8553-b8d2883084c5)

**Comment by DKtric3L** [comment]
Just in case, I'll clarify that I'm using the latest version of the system - https://github.com/AnthonyMonette/TheWitcherTRPG

**Comment by mclemente** [comment]
Yes, I'm using its latest version and I got it working on a brand new world.
Have you changed the Estimations? Or any of the settings?
Does this happen to all tokens or just that one? If it's just that one, could you export its actor's data and upload it here?

**Comment by DKtric3L** [comment]
Please excuse me, while solving this issue, at one of the stages I checked the box "Show only during battle".
I was able to figure this out when I created a new world and compared the checkboxes between the settings of the first world and the new one.

actor.system.derivedStats.hp is the correct setting.
![изображение](https://github.com/mclemente/healthEstimate/assets/105752167/0f18dea5-8bef-4723-9e36-9ad0a76a6ba4)
