### ISSUE TITLE
Weird errors while hovering tokens

### ISSUE THREAD

**Issue by Dyrnwyrm** [mclemente/healthEstimate#182]
**Describe the bug**

**To Reproduce**
Just hover the mouse over a linked actor

**Expected behavior**
Nothing on the console
**Screenshots**
![image](https://github.com/mclemente/healthEstimate/assets/129613553/95ae4eac-93cc-4b33-b132-bfd20506294c)

**Game Specifics (please complete the following information):** 
5e 2.2.1
 Foundry Self Hosted 10.291

My players have issues loading the maps, so i just disable the mod is the only one that is causing red errors on the console

**Comment by mclemente** [comment]
Are you on the latest version of Health Estimate? That error should've been fixed 3 days ago.
Also, that error has nothing to do with loading maps.

**Comment by Dyrnwyrm** [comment]
hmm gonna check

**Comment by mclemente** [comment]
Is there any update on this issue?
