### ISSUE TITLE
GURPS (GGA) Support

### ISSUE THREAD

**Issue by Volksters** [mclemente/healthEstimate#183]
**Describe the bug**
Health Estimate doesn't work on GGA. It doesn't appear at all on hover.

**To Reproduce**
1. Inputting the actor.system.HP.value or any of the variations.
2. Shows nothing when mouse hover.

**Game Specifics (please complete the following information):**
 - GURPS GGA V0.16

**Additional context**
I have tried many ways of inputting the HP value such as (actor.system.HP.value) or (system.HP.value)

**Comment by mclemente** [comment]
Try `actor.system.HP`.

**Comment by Volksters** [comment]
Oh! It works now. Thank you, that was a simple fix.
