### ISSUE TITLE
When scaling feature is turned on the title doesn't show in a consistent place or size

### ISSUE THREAD

**Issue by Zamrod** [mclemente/healthEstimate#184]
If you turn on the scale label for the zoom level feature, the health estimate text doesn't stay at the top (or wherever you have it set), it slowly moves down depending on what zoom level you are at. It also is unaffected by the text size setting except if you zoom in far enough then suddenly the text size setting will apply. It'll suddenly change size dramatically at that zoom level and above.

**Expected behavior**
I would expect the text to stay in the same position relative to the token it is hovering over no matter what the zoom level and for the text size setting to affect the size consistently.

**Screenshots**
Zoomed in with the text size set to 8. Position -65. Scaling on:
![image](https://github.com/mclemente/healthEstimate/assets/12570777/7354df15-8788-4d2f-b62d-4ffedc93aae5)

Same settings Zoomed all the way out:
![image](https://github.com/mclemente/healthEstimate/assets/12570777/ac7d8485-8db2-4b05-b1ba-3c1e5f8048d0)

Position set to -30 with otherwise the same settings as above. Zoomed in to the very first zoom level when the font size setting seems to apply:
![image](https://github.com/mclemente/healthEstimate/assets/12570777/506a8b43-9a52-41ea-8986-58f45bde87c2)

One zoom level out from the above picture:
![image](https://github.com/mclemente/healthEstimate/assets/12570777/84fd8cfb-d026-40a7-ad28-6335d5883859)

Same as the above but zoomed all the way out. Now the text starts to cover a large portion of the token:
![image](https://github.com/mclemente/healthEstimate/assets/12570777/fc89d815-fc25-41db-8564-028c917db6c1)

**Game Specifics (please complete the following information):**
 - dnd5e 2.2.2
 - Foundry 11.305

**Additional context**
I think the key might just be changing the zoom point to the bottom of the text instead of the middle (or maybe the top of the text when below the halfway point of the token?

**Comment by mclemente** [comment]
Yes, it can be improved by a lot. I'll take a shot at changing this when I have the time (~1 month from now).
Back when it was implemented I couldn't find a better way to get the placement right for all 3 positions and it was only tested at the default text size (24).
Also, I appreciate the feedback on the zoom point, that's something I'll test once I get to it.

**Comment by mclemente** [comment]
I've changed the behavior on v31.6 to be more consistent, check it out and let me know if anything is out of place.
