### ISSUE TITLE
Setting JS Rule on a new estimate table removes any estimate from tokens

### ISSUE THREAD

**Issue by daevadragon** [mclemente/healthEstimate#192]
When I create a new estimate table and apply a JS Rule of any of the provided samples, no estimate of any table are shown when hovering over a token.

**To Reproduce**
1. Configure settings to add a new health estimate table
2. Add a JS Rule to the new estimate table
3. Hover over token on scene
4. See no estimate shown above token

**Expected behavior**
The default estimate should persist if the new table and the JS Rule fail. If the JS rule is successful, estimates from the new table should be shown.

![image](https://github.com/mclemente/healthEstimate/assets/114616897/de69581f-e2bc-4ee9-b9c4-b1e3778690ea)
![image](https://github.com/mclemente/healthEstimate/assets/114616897/5329ec42-85e1-4b6e-aadc-4cf5af5c9f27)

**Game Specifics (please complete the following information):**
 - Game System and version: dnd5e 2.2.2
 - Foundry: 10.303
 - Health Estimate: 31.2

**Comment by mclemente** [comment]
I've added error handling to fix this issue, now there will be a warning on the console about this.

As for the JS Rule, this post made me realize that "actor" wasn't part of the JS Rule's scope, so all the samples I've posted weren't valid. I'm sorry for that. I've now added "actor" to the scope, so the samples are all valid and the one you've input for your JS Rule should work now.
