### ISSUE TITLE
red error warning

### ISSUE THREAD

**Issue by GuitarGuyNick** [mclemente/healthEstimate#193]
**Describe the bug**
i just wanted to inform of a red error message 
![image](https://github.com/mclemente/healthEstimate/assets/139762764/1018edb2-fb7a-4bea-9b2f-7b0727d5d507)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Game Specifics (please complete the following information):**
 - Game System and version: pathfinder 2e

**Additional context**

**Comment by mclemente** [comment]
Fixed on 31.4
