### ISSUE TITLE
Health Estimate 31.4 show estimates of all tokens to everyone at all times

### ISSUE THREAD

**Issue by mxvs** [mclemente/healthEstimate#197]
**Describe the bug**
Since upgrading to 31.4 Health Estimate has started showing estimates of all token to everyone, regardless of settings.

**To Reproduce**
- Update to 31.4
- Hover over any token, either as DM or as player
- Get Health Estimate
- Change behavior in settings
- No change, health estimates are still being shown regardless of settings

**Game Specifics (please complete the following information):**
Foundry 11.308
Happens in both Pathfinder 2e 5.4.2 and D&D 5e 2.3.1

**Comment by mclemente** [comment]
Which behavior setting did you change especifically? I couldn't reproduce this by changing "Always Show Estimates" and/or "Show Only on Combat".

There was a bug with the release that was fixed on 31.5, but I am not sure if this issue was fixed with the change.

**Comment by LukasPrism** [comment]
This is happening for me too after updating, I didn't change any settings. 

I then went in and tried setting it to All and then back to NPCs only and it's still showing on player characters. dnd5e 2.3.1

**Comment by mxvs** [comment]
> Which behavior setting did you change especifically? I couldn't reproduce this by changing "Always Show Estimates" and/or "Show Only on Combat".
> 
> There was a bug with the release that was fixed on 31.5, but I am not sure if this issue was fixed with the change.

I can confirm that 31.5 fixes this isssue. It popped up after installing 31.4 without me changing any of the behavior settings. In any case its fixed now!
