### ISSUE TITLE
Allow some NPCs to be excluded from this (for players at least)

### ISSUE THREAD

**Issue by brother-oak** [mclemente/healthEstimate#2]
It would be useful if you could exclude some NPCs / enemies from the display of the health estimate, at least for players. I like the module for use in minion battles etc, but I don't necessarily want my players to know how beaten up the BBEG is. In addition, for some creatures, e.g. Oozes, it won't be apparent what their health levels are.
At the moment if you set the MaxHP to 0, this module won't display for that token. However, this is not useful for actual monsters as having a 0 maxHP value messes up other things.

Having another method that you can set on an actor (or token) basis to exclude them from this module (even if only for PCs) would be really useful

**Comment by mclemente** [comment]
I'll setup a macro similar to the Mark Dead macro that'll make the characters flagged by the macro won't show up to players.
