### ISSUE TITLE
Module Does Not Work and is not throwing an error

### ISSUE THREAD

**Issue by Justeee** [mclemente/healthEstimate#205]
**Describe the bug**
Health estimate has stopped working and showing estimates in one of my game worlds. When I open the console I'm not seeing any errors. To further complicate matters, I have another game world which is replicating the exact same modules and settings as the other but Health Estimate is working perfectly well in that one. 

**Game Specifics:**
 - Game System and version: dnd5e v2.3.1
 - Foundry v11.311

**Comment by mclemente** [comment]
Was that world created before V11? If it did, could you try resetting the Style Settings?

**Comment by LeCentreFranco** [comment]
i've had the same issue since i've updated it last week @mclemente my world was built before V11. i'm not seeing any error in the console it shows as loaded and rendering but nothing displayed on the tokens. i've tried uninstalling and reinstalling the module.

**Comment by cedpat4** [comment]
i've had the same issue since i've updated it last week @mclemente my world was built before V11. i'm not seeing any error in the console it shows as loaded and rendering but nothing displayed on the tokens. i've tried uninstalling and reinstalling the module.

**Comment by cedpat4** [comment]
I've tried resetting it it sorta works but the text is super tiny inside the health bar (i hide it from my players) and a diffirent font from before i think
![image](https://github.com/mclemente/healthEstimate/assets/65502021/6b5356cc-01e8-40ce-8566-fd4862482866)

**Comment by Justeee** [comment]
> Was that world created before V11? If it did, could you try resetting the Style Settings?

This particular world was created before V11 and the other that was working was created after. 

I just reset the settings and it's working perfectly now. Thank you!

**Comment by mclemente** [comment]
@cedpat4 have you reset the settings _inside_ the Style Settings menu or just the main Settings Configuration window?

Otherwise, have you tried changing the Font Size setting?

**Comment by itsmeitmohthy** [comment]
I also had this issue, I reset settings and it fixed it but when I changed the estimations settings (I use different wordage than the default because we came from a home game) it breaks it again. Unsure what the problem could be.

**Comment by mclemente** [comment]
@itsmeitmohthy that's weird. Are you even changing the JS Rules or just the estimations?
Can you send the changes over here?

**Comment by KJTailor** [comment]
Had the same error, resetting the Style settings reverted and fixed it. Thank you

**Comment by itsmeitmohthy** [comment]
> @itsmeitmohthy that's weird. Are you even changing the JS Rules or just the estimations? Can you send the changes over here?

It seemed the issue was linked when having both always show Estimates and Show in Combat Only which... ya I guess that makes sense lol but my issues are all resolved thank you!
