### ISSUE TITLE
Toggle off/on Health Estimate on per token

### ISSUE THREAD

**Issue by Morgan-Farkind** [mclemente/healthEstimate#206]
**Is your feature request related to a problem? Please describe.**
Hi! Love the module! My problem is that I'd like the ability to show Health Estimate at certain times or on certain tokens, rather than only to all tokens or no tokens.

**Describe the solution you'd like**
I'd love it if I can show my players the enemy's health estimates on a per-token basis as a quick setting on the npc's character sheet, as an action HUD element, or on the combat tracker. In a session, I want to be able to make my players roll checks to see health estimates of their enemy in cases where it might not be readily apparent, such as when fighting strange/inscrutable creatures, BBEGs, or just things they haven't come across. That way, when they pass the check, I can enable the estimate on that enemy so they can better strategize. 

**Is this specific to system or is it system agnostic?**
D&D 5e, but this could see use in many systems I suppose

**Additional context**
Nothing else comes to mind!

**Comment by mclemente** [comment]
Check the actor's Prototype Token configs or a token's config for the Estimates tab. Also check the Configure Controls for the Health Estimate tab if you want to set an on-demand shortcut.

**Comment by mclemente** [comment]
Closing as wontfix since this feature already exists.
