### ISSUE TITLE
Always displaying health estimates

### ISSUE THREAD

**Issue by LassoTruth** [mclemente/healthEstimate#21]
The 'Show Estimates' option doesn't seem to be working. 

My preferred setting is having the health estimates only displayed for the players and only for non-player characters. However, no matter which setting I choose, I (GM) always see the health estimates and for player characters as well as non-player characters. Tested this on a new world with only Health Estimate installed, has been going on since upgrade to 0.8.+

Thank you for the module, it's wonderful.

**Comment by mclemente** [comment]
Thank you for reporting it, it's fixed now.
