### ISSUE TITLE
No estimates showing in latest PF2E version

### ISSUE THREAD

**Issue by laurieathey** [mclemente/healthEstimate#210]
**Describe the bug**
Health estimates not appearing.
We're in PF2E, on version 5.7.3

**To Reproduce**
As best I can tell it's because the PF2E system has changed something to do with stamina. You currently can't set bars to display the characters stamina either and there's a bug for it here https://github.com/foundryvtt/pf2e/issues/10763

**Expected behavior**
Should show health estimates in PF2E including stamina on the latest version 

**Screenshots**
No estimate for my near death monkey monk :( 
![image](https://github.com/mclemente/healthEstimate/assets/11553364/11a0b4c3-e8bb-430a-be99-cec2d6f1e83c)

**Game Specifics (please complete the following information):**
We're in PF2E, on version 5.7.3 foudnry 
![image](https://github.com/mclemente/healthEstimate/assets/11553364/7547b4bf-e6cd-42b7-af32-96c5425ab18d)

**Comment by mclemente** [comment]
Are you on the latest version of Health Estimate? This was reported and fixed yesterday #209.

**Comment by laurieathey** [comment]
I should be. I hit "Update All" on my systems and mods this morning. 
Checking again... Yup
![image](https://github.com/mclemente/healthEstimate/assets/11553364/744cc9a0-ef7e-459f-83c8-74f05e4d55b1)
I'm on V31.7.2 which appears to be latest at the time of writing this.

The only difference between now and that bug is that one was reported for 5.7.2 of PF2E and I'm on 5.7.3?

**Comment by mclemente** [comment]
It seems to be working for me. Are there any errors on the console?

**Comment by laurieathey** [comment]
Ah crap, I forgot to post the error. Sorry.
```
foundry.js:753 TypeError: Error thrown in hooked function '' for hook 'setup'. Cannot read properties of undefined (reading 'warn')
    at HealthEstimate.updateSettings (logic.js:352:22)
    at HealthEstimate.setup (logic.js:34:8)
    at Object.fn (healthEstimate.js:10:47)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.setupGame (foundry.js:8654:11)
    at async Game._initializeGameView (foundry.js:9931:5)
```

**Comment by laurieathey** [comment]
Nice! I can confirm this fixed it :) 
This caused 3 new errors at first but when I read the preceeding warning it just said that I needed to go into your style settings to choose a font (which was set but I guess I needed to go hit save or something)

Anyway, we now have a badass metal font 👍 
![image](https://github.com/mclemente/healthEstimate/assets/11553364/29397c86-00ab-4fb5-86f7-1d091bc7d5c0)
