### ISSUE TITLE
libWrapper error on loading world, health estimate does not work

### ISSUE THREAD

**Issue by nschoenwald** [mclemente/healthEstimate#214]
Using current version of foundry v11 and dnd5e system.
<img width="471" alt="image" src="https://github.com/mclemente/healthEstimate/assets/72390280/46b5f889-5f84-4c99-b146-e7342f041c9e">

**Comment by nschoenwald** [comment]
Update: This was fixed by changing the font settings reloading. Still something that could be worth fixing in the module itself.

**Comment by mclemente** [comment]
This issue was fixed on 31.7.8, thanks for reporting it.
