### ISSUE TITLE
Red errors in console, but every thing still seems to work

### ISSUE THREAD

**Issue by dracolumina** [mclemente/healthEstimate#215]
So I am getting this in the console when I "update any actor" with module installed, not sure if its conflicting with another module or not.
![image](https://github.com/mclemente/healthEstimate/assets/7224999/8d7dc25e-87e9-44da-bfcb-bbbd89d1f84d)

**Comment by mclemente** [comment]
It seems there is a token with an actor that somehow doesn't have an id but still triggers the updateActor hook. Seems weird.
Anyway, I've pushed an update that tries to fix this issue, check it out and let me know if the issue persists.

**Comment by dracolumina** [comment]
no more Red!!! thanks for the quick update
