### ISSUE TITLE
Health estimate no longer showing on tokens

### ISSUE THREAD

**Issue by Quinn-Aetherwood** [mclemente/healthEstimate#216]
**Describe the bug**
No estimate shown anymore. 
**To Reproduce**

**Expected behavior**
Expected to see health estimates. I haven't changed mod lists. 

**Screenshots**
![image](https://github.com/mclemente/healthEstimate/assets/127997499/de3eff00-5325-4605-8566-c086dfa2d92e)

**Game Specifics (please complete the following information):**
 - Game System and version: [e.g. dnd5e 1.3.6]
 - v11 stable 314
 - dnd5e 2.3.1

**Additional context**

**Comment by mclemente** [comment]
Seems to be a repeat of #214. This issue should be fixed now.

**Comment by Quinn-Aetherwood** [comment]
Hello. I updated modules but health estimate is still not showing. Just thought i'd let you know if it should be fixed now.
