### ISSUE TITLE
May be intentional, but setting Health Estimate settings on Prototype tokens doesn't stick, while setting them on the placed token will.

### ISSUE THREAD

**Issue by EmoCthulhu** [mclemente/healthEstimate#217]
If I set any of the 3 options for Health Estimate on a prototype token, when the token is placed on the canvas, they won't be enabled. In fact opening the character sheet again, and hitting prototype token again, none of the boxes will be checked. If you double click a token on the map, then go to token, you can enable the settings there, and they will work as expected.

Would be great if I could set all my monsters in my bestiary to Hide Name, and then drop them at will, knowing the Hide Name will be checked.

Game Systems: Simple Worldbuilding, Dragonbane (only ones of my 10 tested so far). Happens on both my local Foundry as well as my Forge hosted games. Foundry v11 Build 313.

**Comment by mclemente** [comment]
> If I set any of the 3 options for Health Estimate on a prototype token, when the token is placed on the canvas, they won't be enabled. In fact opening the character sheet again, and hitting prototype token again, none of the boxes will be checked. If you double click a token on the map, then go to token, you can enable the settings there, and they will work as expected.

I couldn't replicate this issue with Don't Mark as Dead and Hide Estimates on a world on the dnd5e system.

> Would be great if I could set all my monsters in my bestiary to Hide Name, and then drop them at will, knowing the Hide Name will be checked.

There was an issue with the Hide Names option, it is correctly set but shows up as uncheked when re-opening. This means the bug is only visual, unless you save without checking the box again.

Also, you can change Default Token Settings so you won't need to check them for every character. Especially useful if you're already done creating PCs or don't care about unchecking it for the PCs.

**Comment by EmoCthulhu** [comment]
Yes I discovered the real behaviour later last night, but was going to wait
until tonight to edit my post on GitHub. I find it annoying to have to
check the box every time I change something on a token, because I'm usually
not changing Health Estimate settings. I'm more likely to be changing
whether it shows on TokenBar or the token's disposition if players deal
with the NPC and change his mood from hostile to neutral for example.

I also made a beta world for The Walking Dead Universe using Simple World
Building, and I have noticed that for player characters, setting Hide Names
doesn't hide the name. It hides it for all other types, NPC's, Walkers,
Animals. All of my templates for Actors were created before I added Health
Estimate as a module. This happens in Dragonbane as well, just tested now.
Player Characters cannot be set to Hide Names. I may have missed something
in your release notes or read me, and this is intentional. In my testing
just now, I also created characters and checked characters that I know were
created after adding Health Estimate. Not even sure how it's
differentiating between NPC's, Animals, Walkers and PC's in The Walking
Dead as all Actor types are set to 'character.' I thought maybe it was
Friendly disposition, but I tried changing some PC's to hostile, and still
can't get it to Hide Names.

Anyway, thanks for the quick response. I've also noticed that doing as you
said, setting Default Token Settings to have Hide Names, it's still the
same thing, as long as you make sure to check it again before saving it
will work, but if you ever go back to make any changes, you have to check
it again before hitting save.

**Comment by mclemente** [comment]
It is intentional that tokens of player owned actors don't have their names hidden.

**Comment by EmoCthulhu** [comment]
Thank you for the clarification. A nice touch.
