### ISSUE TITLE
Console Spam from actorless tokens

### ISSUE THREAD

**Issue by ImaginaryfriendOnline** [mclemente/healthEstimate#22]
Right now if you use a lot of Actorless tokens (like, for instance with Token Attacher), the console filles up rapidly with messages like:

> logic.js:135 Health Estimate | dungeon has no actor.
> logic.js:135 Health Estimate | dungeon has no actor.

While not useless messages, the usefulness diminishes rapidly, and an option to turn this spam off would be a boon

**Comment by mclemente** [comment]
You could use the Hide Estimate macro to avoid it. Just select all the actorless tokens and use the macro once and the spam will be gone.

**Comment by ImaginaryfriendOnline** [comment]
I can, and I can just comment out the console log line, which I did. And which I will just do again on update if needed. But...
Some scenes have multiple dozens of actorless tokens, making a macro rather far removed from user-friendly. I get the need for debug information, but in a production module, the option of turning debug information off is kinda nice.

**Comment by ImaginaryfriendOnline** [comment]
Thank you :) I appreciate the fix, and I appreciate this module and your effort immensely!
