### ISSUE TITLE
Add support for pathfinder 1e vigor system

### ISSUE THREAD

**Issue by Snogard** [mclemente/healthEstimate#223]
**Is your feature request related to a problem? Please describe.**
If i use the pathfinder 1e vigor system, the module still uses hp to estimate the health status

**Describe the solution you'd like**
One of the following:
- The module autodetects if the vigor system is enabled or not and uses vigor + wounds to estimate health
- Add two formula fields, one for current and one for max health, where i could specify a formula using actor variables

**Is this specific to system or is it system agnostic?**
The second solution would be system agnostic

**Comment by mclemente** [comment]
How does the system work exactly? How do the wounds affect health?

**Comment by Snogard** [comment]
Essentially you have 2 hp pools, each works different mecchanically see -> [wound and vigor](https://www.d20pfsrd.com/gamemastering/other-rules/wounds-and-vigor/)


Here i made an harcoded version of the faction method:
```
fraction(token) {
   const vigor = token.actor.system.attributes.vigor;
   const wounds = token.actor.system.attributes.wounds;
   let addTemp = 0;

   if (sGet("core.addTemp")) {
      addTemp = vigor.temp;
   }
   return (vigor.value + wounds.value + addTemp) / (vigor.max + wounds.max)
}
```
