### ISSUE TITLE
[Feature Request] Hide "Uninjured" when always show is selected

### ISSUE THREAD

**Issue by mnoreke** [mclemente/healthEstimate#224]
It would be nice to have an additional feature setting to hide the status for full health tokens, so that the estimate only exists for injured/damaged tokens.

**Comment by mclemente** [comment]
Just change the highest estimate's % to 99.

**Comment by mnoreke** [comment]
> Just change the highest estimate's % to 99.

This works for when placing a token on the map, but it doesn't clear the text for me when healing an injured token up to full health. I also tried creating a tier for 100% with blank text.

**Comment by mclemente** [comment]
Now that's a bug, it should clear the tooltip. I'll get it fixed. Thank you.
