### ISSUE TITLE
Inconsistent Placement and Font Size With Different Grid Sizes

### ISSUE THREAD

**Issue by Red5MT** [mclemente/healthEstimate#236]
The Style Settings only work well for one grid size. Changing the grid size alters where the estimate is displayed. I originally configured my world and Helath Estimate with a grid of 200px. At one point, I wanted to use a very large map for a scene, so I reduced the resolution and grid size to 100px, but Health Estimate dropped the estimate into the square below the token. See screenshots.

I chose to display the estimate at the bottom of the token, which is a big reason why I am having the problem. If I were to leave it at the top of the token, it would be displayed relative to the top. Also, since the Font size is a set value and not relative to the grid size, it is also not rendered consistently between different grid sizes. I understand this is all due to how the configuration is set up. You are using finite numbers instead of values relative to the grid size.

 - Game System: DnD5e v2.3.1
 - Foundry VTT v11.315
 - Health Estimate v31.3

![HealthEstimate200pxGrid](https://github.com/mclemente/healthEstimate/assets/83143296/37b190c1-18ea-4d8d-a0e7-c9cf9d59762f)
![HealthEstimate100pxGrid](https://github.com/mclemente/healthEstimate/assets/83143296/cb173bfd-141c-4495-ab86-736965ae12c4)
![HealthEstimate200pxConfig](https://github.com/mclemente/healthEstimate/assets/83143296/905bdbea-7197-45cf-8265-a12964355139)

I really liked this module. I was able to pull off some fun and slick stuff using it. However, I also want to present a clean, tight game. This issue is a deal breaker for me. I figured I would at least share the issue.

**Comment by mclemente** [comment]
> Health Estimate v31.3

Is there any reason you're not using the latest Health Estimate version? I've fixed that issue on October.

**Comment by Red5MT** [comment]
Ignorance mostly...   :)
I am still finding my way around Foundry...and I **thought** the Add-on Module section would tell me when an update was available for a module. I will check out the update. Thanks (and sorry).

**Comment by Red5MT** [comment]
Just looked at the updated version. Placement is definitely better. Font is still larger/smaller relative to the size of the grid.

**Comment by mclemente** [comment]
The module assumes people aren't using different grid sizes for each scene. Foundry itself only increases displayed names' font size by 4px, but everything else doesn't scale, like the text on Text Drawings.

Changing that behavior to scale based on grid size means I'd have to pick 100 as the baseline and that would impact every user on different grid sizes that already configured their font sizes.
I'd also need to introduce a new "Default Grid Size for scaling" setting or risk having the Font Size setting being inaccurate for non-default grid size.

I suggest you avoid changing grid sizes unless you really need to and, whenever you do, change your font size accordingly.

**Comment by Red5MT** [comment]
I understand. The font 'issue' is less important than the placement was, so it's nice that you had that fixed.

Thanks for the mods btw. It takes a lot of time and effort to make and maintain them. It is appreciated.

**Comment by mclemente** [comment]
I've went back on this and am now adding the grid size scaling feature, although it is disabled by default.

**Comment by Red5MT** [comment]
Works great. Thank you for the feature.
