### ISSUE TITLE
No longer working in ~~DnD5e or~~ Level Up A5e 

### ISSUE THREAD

**Issue by igotsmeakabob11** [mclemente/healthEstimate#243]
**Describe the bug**
No longer works. 

**To Reproduce**
Check error log.
https://cdn.discordapp.com/attachments/964191150586089553/1230457834781540424/image.png?ex=66336428&is=6620ef28&hm=cc593daa4b7e1b37724455b9de9b480153457a9b73cae0a8199469346ca2c9de&

**Expected behavior**

**Screenshots**

[If applicable, add screenshots to help explain your problem.](https://cdn.discordapp.com/attachments/964191150586089553/1230457834781540424/image.png?ex=66336428&is=6620ef28&hm=cc593daa4b7e1b37724455b9de9b480153457a9b73cae0a8199469346ca2c9de&)
![image-68](https://github.com/mclemente/healthEstimate/assets/116937548/5ac7bdf4-0be4-4bdd-b3c8-da5f35d8a25b)

**Game Specifics (please complete the following information):**
 - DnD5e latest, a5e latest
 - newest update

**Additional context**
Hey, I know other users are experiencing the issue- I'm not too experienced in the technical matters but I love the module and hate when it's not working 😆

**Comment by mclemente** [comment]
Can you try reinstalling? That method shouldn't be called on either system, only on Custom System Builder and the system-agnostic provider. Even then, it _should_ be available since it is defined on the base class.

**Comment by igotsmeakabob11** [comment]
That error provided above was someone else's who was experiencing the issue. I uninstalled and reinstalled, still not working. However my 5e game IS working :( 
Here are errors on the Level Up a5e system: 
![image](https://github.com/mclemente/healthEstimate/assets/116937548/af63c581-5f73-4fad-8d06-204dba550b3d)
![image](https://github.com/mclemente/healthEstimate/assets/116937548/edd68844-eabb-4e3e-96e4-7da43ebac9a4)
