### ISSUE TITLE
Estimates not Showing

### ISSUE THREAD

**Issue by ChrisEurolog** [mclemente/healthEstimate#244]
**Describe the bug**
Estimates not showing.

**To Reproduce**
They never show, no error reported in DevTools (F12)

**Expected behavior**
Display status (Injured etc.)

**Screenshots**

**Game Specifics (please complete the following information):**
 - Game System and version: PF2e 5.15.2
 - Module Version 31.8.8

**Additional context**
It was working, but some time ago - was hoping an update would fix it but no luck!

**Comment by mclemente** [comment]
Have you had any luck with this? I haven't managed to reproduce this error back then, and there were no changes to the PF2e provider since 31.8.0.

**Comment by ChrisEurolog** [comment]
I managed to discover a workaround. If I switch the text to RGB, they show again. Switching them to B&W makes them disappear

**Comment by mclemente** [comment]
Hm, still couldn't reproduce it. That's super odd, disabling colors doesn't change anything in the way the module works.
Could you try resetting the Style Settings and then disabling the colors?

**Comment by ChrisEurolog** [comment]
Sorted, thanks!
