### ISSUE TITLE
Incorrect Link on Foundry Page

### ISSUE THREAD

**Issue by jrixie** [mclemente/healthEstimate#245]
**Describe the bug**
On foundry page (https://foundryvtt.com/packages/healthEstimate) clicking the link in the Supported Systems section titled "module's repo" leads to `https://github.com/mclemente/healthEstimate/issues.` (note the additional . at the end). Removing the . and reloading the page correctly links to here!

**Comment by jrixie** [comment]
Also thanks for the awesome module! Exactly what I'm looking for!

**Comment by mclemente** [comment]
LOL, thank you, it's fixed now :D
