### ISSUE TITLE
An option to specify which estimation settings apply to tokens

### ISSUE THREAD

**Issue by OxTailSafu** [mclemente/healthEstimate#247]
Hey there, great mod and look forward to trying it some more. I was wondering if there could be a setting in place that'd allow the dm to choose if certain health estimations apply to player characters or npcs.

![image](https://github.com/mclemente/healthEstimate/assets/123988485/d8a1b03d-632e-478a-8e4a-f30b97f01baa)

For example, here I have it set so that there are 3 ranges for the game. I understand that you can choose if the estimates apply to either player characters & npcs, however there I think it'd be great if you can further specify if say for instance, only the 50% health estimate applies to npcs while pc's can utilize all 3.

Apologies if I'm not making much sense or if this is already a setting in place, but I appreciate the consideration all the same!

**Comment by mclemente** [comment]
1. Add another table
2. Only input the 50% estimate
3. Set its JS Rule to `type === "npc"`

**Comment by OxTailSafu** [comment]
Oh this is great! Thank you so much, and just for future reference. For player characters, would it be `type === 'pc'?

**Comment by mclemente** [comment]
It depends on the system. On dnd5e, it is `character`. You can check all the actor types in a system by inputting `Object.keys(CONFIG.Actor.sheetClasses)` on the console, ignoring the `base`.

You're welcome. If that's all, I'll be closing this issue.
