### ISSUE TITLE
Feature Request: Show to All (NPC only)

### ISSUE THREAD

**Issue by fylson** [mclemente/healthEstimate#25]
Hi. Is it possible to insert an option, where you can select "Show to all, NPC only"? I want to show estimates on NPC´s only, but want to see it as GM too. Is that possible?

For exable to split the "Show Estimate" options into two, one you can select who can see it and annother, on wich token you see it?

**Comment by mclemente** [comment]
Thanks, it's done now.
Back when I took over the module, it used to be 4 redundant settings (GM-only, Player-only, PC Tokens, NPC Tokens), then I merged all into a single one, but it hasn't crossed my mind splitting it in two would've been better.
