### ISSUE TITLE
V32.5 not working

### ISSUE THREAD

**Issue by GregoryWarn** [mclemente/healthEstimate#257]
**Describe the bug**
Health Estimate v32.5 is not working on my system.
After updating at v32.5 (the only module updated today), estimate on token disappeared, so I opened Foundry Modules setup and I found only 3 buttons (only the middle one opens a window, if I click the other 2 nothing happens).
PS: I rolled back at v32.4 and it's working great as usual!

**Screenshots**
- Foundry Module setup window (Italian Localization)
- Console errors
![Screen Shot 08-14-24 at 10 58 AM](https://github.com/user-attachments/assets/fdb38dd1-c6b1-40c7-a0d7-827a80533fec)
![Screen Shot 08-14-24 at 11 02 AM](https://github.com/user-attachments/assets/e60e0360-6d0a-4f32-8f3e-e2f465ff34e3)

**Game Specifics:**
 - Game System and version: Foundry v12.330 - D&D5e v3.3.1
 - Module Version v32.5

**Comment by TheFehr** [comment]
I can confirm this.
I get the following on boot up of the world:
`Uncaught (in promise) Error: "healthEstimate.core.menuSettings.fontSize" is not a registered game setting
[Detected 2 packages: healthEstimate(32.5), lib-wrapper(1.12.15.0)]
    #assertKey foundry.js:3402
    set foundry.js:3369
    sSet utils.js:68
    ready logic.js:95
    <anonymous> healthEstimate.js:11
    #call foundry.js:632
    callAll foundry.js:589
    setupGame foundry.js:9097
    _initializeGameView foundry.js:10431
    _initializeView foundry.js:10407
    initialize foundry.js:8994
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:805
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:95938
    async* foundry.js:95918
[foundry.js:3402:42](https://vtt.thefehr.ch/scripts/foundry.js)`
`Uncaught (in promise) Error: "healthEstimate.core.menuSettings.position" is not a registered game setting
[Detected 2 packages: healthEstimate(32.5), lib-wrapper(1.12.15.0)]
    #assertKey foundry.js:3402
    set foundry.js:3369
    sSet utils.js:68
    ready logic.js:105
    <anonymous> healthEstimate.js:11
    #call foundry.js:632
    callAll foundry.js:589
    setupGame foundry.js:9097
    _initializeGameView foundry.js:10431
    _initializeView foundry.js:10407
    initialize foundry.js:8994
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:805
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:95938
    async* foundry.js:95918
[foundry.js:3402:42](https://vtt.thefehr.ch/scripts/foundry.js)`
`Uncaught (in promise) Error: "healthEstimate.core.menuSettings.position2" is not a registered game setting
[Detected 2 packages: healthEstimate(32.5), lib-wrapper(1.12.15.0)]
    #assertKey foundry.js:3402
    set foundry.js:3369
    sSet utils.js:68
    ready logic.js:106
    <anonymous> healthEstimate.js:11
    #call foundry.js:632
    callAll foundry.js:589
    setupGame foundry.js:9097
    _initializeGameView foundry.js:10431
    _initializeView foundry.js:10407
    initialize foundry.js:8994
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:805
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:95938
    async* foundry.js:95918`

**Comment by mclemente** [comment]
I can't reproduce this error at all, I've tried it on a new world and it works as normal. Somehow the function that registers the settings isn't being called, even though nothing was changed there at the setup method.

**Comment by incendium** [comment]
This seems to be the very first error I am seeing in the console related to this issue:

```
Error: Error thrown in hooked function '' for hook 'setup'. game.modules.get(...) is undefined
[Detected 2 packages: healthEstimate(32.5), lib-wrapper(1.12.15.0)]
    onError foundry.js:654
    call_wrapped libWrapper-wrapper.js:507
    <anonymous> listeners.js:140
    onError#0 libWrapper-wrapper.js:187
    #call foundry.js:636
    callAll foundry.js:589
    setupGame foundry.js:9059
    _initializeGameView foundry.js:10431
    _initializeView foundry.js:10407
    initialize foundry.js:8994
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:805
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:95938
Caused by: TypeError: game.modules.get(...) is undefined
[Detected 2 packages: healthEstimate(32.5), lib-wrapper(1.12.15.0)]
    registerSettings settings.js:44
    setup logic.js:74
    <anonymous> healthEstimate.js:10
    #call foundry.js:632
    callAll foundry.js:589
    setupGame foundry.js:9059
    _initializeGameView foundry.js:10431
    _initializeView foundry.js:10407
    initialize foundry.js:8994
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:805
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:95938
foundry.js:655:30
```

**Comment by arcanjl** [comment]
Me too
BaseV2.js:52 Uncaught (in promise) TypeError: undefined. Cannot destructure property 'name' of 'settingData(...)' as it is undefined.
[Detected 3 packages: healthEstimate(32.5), colorsettings(3.0.3), lib-wrapper(1.12.15.0)]
    at HealthEstimateBehaviorSettings.prepSetting (BaseV2.js:52:11)
    at HealthEstimateBehaviorSettings._prepareContext (BehaviorSettings.js:25:21)
    at #render (foundry-esm.js:44306:34)
    at Semaphore._try (foundry-esm.js:6645:25)
    at foundry-esm.js:6617:21
    at new Promise (<anonymous>)
    at Semaphore.add (foundry-esm.js:6615:14)
    at HealthEstimateBehaviorSettings.render (foundry-esm.js:44278:30)
    at MonksSettingsConfig.onClickSubmenuWrapper (colorSetting.js:21:24)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)
    at 🎁SettingsConfig.prototype._onClickSubmenu#0 (libWrapper-wrapper.js:189:20)
    at HTMLButtonElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)

**Comment by mclemente** [comment]
I found the issue: cd41825702135e4462dc868369184d40ff159a04
It wasn't happening to me because I had the module installed 🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

A new version with the fix is out now. Sorry everyone for your troubles.

**Comment by arcanjl** [comment]
No problem at all! Thank you so much for fixing it so fast
Sent from my iPhone

On Aug 14, 2024, at 2:32 PM, Matheus Clemente ***@***.***> wrote:

﻿

I found the issue: cd41825<https://github.com/mclemente/healthEstimate/commit/cd41825702135e4462dc868369184d40ff159a04>
It wasn't happening to me because I had the module installed 🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

A new version with the fix is out now. Sorry everyone for your troubles.
