### ISSUE TITLE
Lancer gamesystem now uses token.actor.hp instead of token.actor.derived.hp

### ISSUE THREAD

**Issue by Cupax3** [mclemente/healthEstimate#259]
**Describe the bug**
When using the Lancer gamesystem in its current version, the module tries to access an invalid attribute and doesn't work.

**To Reproduce**
1. Use Foundry V11.315
2. Install LANCER ~2.2.4
3. Install healthEstimate ~31.8.9
4. Hover over token
5. Look at console
6. See error

**Expected behavior**
The health estimate text to appear.

**Game Specifics (please complete the following information):**
 - Game System and version: LANCER 2.2.4
 - Module Version: 31.9.9

**Additional context**
Fix:
`/src/module/providers/lancer.js`
`L10: const hp = token.actor.system.derived.hp; -> const hp = token.actor.hp;`
Though that does not take into account whether behaviour for older LANCER versions using up-to-date healthEstimate should remain unchanged. I was unable to determine which version of LANCER introduced the breaking change, and do not know enough about Foundry modules to implement a version check, hence no PR.

**Comment by mclemente** [comment]
A fix is out, but you will need to reinstall the module since updating will only pick up on the V12-only version of the module.
