### ISSUE TITLE
when using the mod for health it hides height values in pf2e.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [mclemente/healthEstimate#263]
**Describe the bug**
when you are using the mod the injured status above the token hides the height values. this happens in pf2e but it could happen in other systems. 

**To Reproduce**
1. type in height
2. make the creature damaged
3. see the conflict between height value and the injured status.
4. you cant see the height value. which is very useful for gms and players.

**Expected behavior**
if a height value is used it should be above the status value.

**Screenshots**
![image](https://github.com/user-attachments/assets/5be227e5-f190-4839-a0dc-20b207f7c24b)

<img width="615" alt="{8BC0D62E-3628-41BA-9173-307934B4E1A3}" src="https://github.com/user-attachments/assets/abe1f859-468c-41e3-9e34-546d104edbd9">

**Game Specifics (please complete the following information):**
 - Game System and version: [e.g. dnd5e 2.4.1]
 - Module Version [e.g. 31.7.11]

**Additional context**

**Comment by mclemente** [comment]
There is the "Elevation Tooltip Position" setting to change the position the tooltip gets rendered.

Alternatively, you can change the estimate's position by changing its Height to a negative value under the Style Settings menu.
E.g. this is what -20 looks like
![image](https://github.com/user-attachments/assets/daf04106-736a-436e-830d-da802a13b538)

**Comment by ThingsCouldGetDicey** [comment]
> There is the "Elevation Tooltip Position" setting to change the position the tooltip gets rendered.
> 
> Alternatively, you can change the estimate's vertical position by changing its Height to a negative value under the Style Settings menu. E.g. this is what -20 looks like ![image](https://private-user-images.githubusercontent.com/5288872/367473377-daf04106-736a-436e-830d-da802a13b538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNzI5MTcsIm5iZiI6MTcyNjI3MjYxNywicGF0aCI6Ii81Mjg4ODcyLzM2NzQ3MzM3Ny1kYWYwNDEwNi03MzZhLTQzNmUtODMwZC1kYTgwMmExM2I1MzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTRUMDAxMDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZkNWJjMmZmMDk1MWE3N2RlMDMyMTVmMzRkZThjMTZmNjM0NTg1YzA5MGRiMGRjNGU3MmRjMTQ0YWFmYTE2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eauVKKSc_VkGoSyidtW9fE3GBnC8pLMGVOHbux45lP0)

thank you doing +30 on it looks good. do you think this could be the default? as it fixes that issue.

**Comment by mclemente** [comment]
I won't change the default position because Elevation isn't that widely used. I'd rather leave it to the user to change it in the settings, since the Elevation position is simpler than changing the estimate's position.
