### ISSUE TITLE
Star Wars FFG System Support?

### ISSUE THREAD

**Issue by Sonny-Crockett** [mclemente/healthEstimate#3]
[@actor.data.data.stats.wounds.value] [@actor.data.data.stats.wounds.max]

Could we get support for the FFG Star Wars system please?

**Comment by mclemente** [comment]
Sure! I need some more info:
Does the system have some kind of temporary hit points?
Wounds are counted from 0 to max, right?
Is Hull Trauma the ship's equivalent of hp?

**Comment by Sonny-Crockett** [comment]
Temp HP, I don't think so.

Yes strain and system strain can be ignored for "HP" concerns. Wounds are counted up, correct so someone with 0 wounds has 100% hp. 

Hull Trauma is "Wounds" for ships. 

https://eote.bgsemc.com/rules/health - link for more info

**Comment by mclemente** [comment]
Thanks, I've updated the module. Please, check if there's anything weird with the system.

**Comment by Sonny-Crockett** [comment]
It is working, but looks like my NPCs are coming up as Vehicles? It's showing "Pristine" instead of "Uninjured". 

Let me know if you need any info to help out. I mean it is perfectly usable as is, just figured I would report it.

**Comment by mclemente** [comment]
Got it. The [description logic](https://github.com/mclemente/healthEstimate/blob/master/module/systems/starfinder.js#L65) looks if the token's type isn't "character" or "npc", SWFFG NPC's are "minion" instead, so it is considered a vehicle instead because it worked back then with Starfinder.

**Comment by Sonny-Crockett** [comment]
Oh great catch. Do I need to update anything on my end?

**Comment by mclemente** [comment]
Just update the module.

**Comment by Sonny-Crockett** [comment]
![image](https://user-images.githubusercontent.com/39606970/115116109-ef493e00-9f65-11eb-89ea-fed303b6b526.png)

Its working great! Thank you so much.
