### ISSUE TITLE
Feature Request - Tint the token based on the current state HP

### ISSUE THREAD

**Issue by p4535992** [mclemente/healthEstimate#32]
Can you integrate as an additional setting the possibility of changing the backgorund coloring of the token based on the state of health estimate (as is the case for the writing in the nameplate to understand)?

Basically I would like the same feature offered by https://github.com/Nazacra/hitpoint-tint, but synchronized with the health estimate states.

Why this? Many players are blind and do not read the text label, but they see the color variation in the token ....

I don't know exactly how to manage it ... maybe giving the possibility to choose which states to activate the coloring is the most custom method that comes to mind.

**Comment by mclemente** [comment]
It's doable, I just have to figure out how to set up another color palette, because it's currently using the red-green palette, where a 100% token is green-tinted instead of transparent.

**Comment by p4535992** [comment]
Close this because nobody seem to want this XD
