### ISSUE TITLE
Feature Request - Toggle "Critical NPCs" to use PC Tracks

### ISSUE THREAD

**Issue by Golurkcanfly** [mclemente/healthEstimate#35]
This is simply a feature to allow you to designate important NPCs to use the PC injury track instead of marking them as dead like regular NPCs when they hit 0 HP.

**Comment by mclemente** [comment]
You can toggle `Death State on Condition` on and the `NPCs die immediately` off in the Death Settings to accomplish this. Otherwise, the solution will be to use a macro which would be similar to the `Hide Estimate` macro.
