### ISSUE TITLE
Unable to use Health Estimate Since Last Week.

### ISSUE THREAD

**Issue by TheMathKing** [mclemente/healthEstimate#38]
Last week I was able to use health estimate, but since then something has changed and I am unable to access the settings for the module, nor am I able to see the health estimates. The module appears in my list of installed modules, it also appears in teh Data\modules\ folder.

When I load foundry I get the following error corresponding to health estimate:

healthEstimate.js:1 GET http://localhost:30000/modules/healthEstimate/module/settings.js net::ERR_ABORTED 404 (Not Found)
healthEstimate.js:2 GET http://localhost:30000/modules/healthEstimate/module/preloadTemplates.js net::ERR_ABORTED 404 (Not Found)
healthEstimate.js:3 GET http://localhost:30000/modules/healthEstimate/module/systemSpecifics.js net::ERR_ABORTED 404 (Not Found)
healthEstimate.js:4 GET http://localhost:30000/modules/healthEstimate/module/logic.js net::ERR_ABORTED 404 (Not Found)

Do you know what is going on?

**Comment by mclemente** [comment]
Try reinstalling, it seems it installed incorrectly, because it is missing some files.
