### ISSUE TITLE
Support for Cyberpunk Red Core system

### ISSUE THREAD

**Issue by Dadrak** [mclemente/healthEstimate#41]
**Descritpion:**

Support for the Cyberpunk Red Core System

**Proposed Feature:**

Cyberpunk Red compared to other systems has not only HP, but also a Wound State system. This means that the module doesn't work with the system.

Here is the System's Gitlab : https://gitlab.com/JasonAlanTerry/fvtt-cyberpunk-red-core

Here is the System's FoundryVTT page : https://foundryvtt.com/packages/cyberpunk-red-core

I understand that you have other priorities and that this is only a small flavor enhancement, still I hope you take it under consideration and as always thank you for your hard work.

**Comment by mclemente** [comment]
How does it work for each actor?  
Do Black ICE and Demons have HP or do I just use Rez?  
How do HP and Wounds interact? I can't really show both states currently, but I can make the worst state to show up.

**Comment by Dadrak** [comment]
Hello there,

Thank you for taking the time to respond to me.

So Demons and Black Ice have only Rez, no HP or wound states, so there is no need to modify them or add anything to them, in my opinion.

Actors use a wound and HP system. As lower their HP gets the worse their wounds get. First is "not wounded", after that comes "Lightly wounded", after this comes "Seriously Wonded" and finaly at 0 HP comes the "mortally wounded" state.

I've recorded a video to help see it more clearely. Again thx for taking the time and I hope I'm able to help you in your work.

https://user-images.githubusercontent.com/93881828/141293765-3bb29dac-43bf-40ea-a1b3-12689faf0e04.mp4

**Comment by mclemente** [comment]
Could you download this version and try it? https://github.com/mclemente/healthEstimate/archive/264ef451efafc48e10c04b72254ec22d76d81f89.zip  
It uses the system's states by default, but you can toggle a setting to use the module's.

**Comment by Dadrak** [comment]
it works man thx

**Comment by mclemente** [comment]
It'll be on the next update, should be out this week.

**Comment by Dadrak** [comment]
that is music to my ears man, thank you for the work
