### ISSUE TITLE
Death overlay not appearing on tokens when they hit 0

### ISSUE THREAD

**Issue by TaakoMagnusen** [mclemente/healthEstimate#42]
Foundry 0.8.9
Health Estimates 26.12

 Steps to reproduce

1) Place token on field
2) Reduce to 0 health

"Dead". text appears but no skull icon overlay

In "Death Settings" i have "NPCs die immediately" checked and my Death Marker is `icons/svg/skull.svg`

**Comment by mclemente** [comment]
The module doesn't do that. https://github.com/mclemente/healthEstimate/wiki/How-To's

**Comment by TaakoMagnusen** [comment]
I see, i guess i'm confused why HE wants a path to a "death marker" in the dead settings for it if its not for the overlay.
