### ISSUE TITLE
Allow more than one resource (Stamina + HP) to be taken into consideration

### ISSUE THREAD

**Issue by JerkyGunner** [mclemente/healthEstimate#48]
It would be great to allow actors that have two pools of "health" - such as PCs who have both Health and Stamina - to be able to have their estimate calculated using the combined pools rather than only the Health.

**Comment by mclemente** [comment]
Which system are you on? At least the systems with Temporary HP allow you to do that.

**Comment by JerkyGunner** [comment]
I'm on Pathfinder 2E using the Stamina variant rule. It basically splits the HP pool into HP and SP but they're two separate resources. However they take damage in the same way (it's just healing that works a bit differently).
