### ISSUE TITLE
Perhaps I am doing it wrong, or bug

### ISSUE THREAD

**Issue by galaara98** [mclemente/healthEstimate#55]
![image](https://user-images.githubusercontent.com/178406/148663877-6b738f65-ee9b-463e-8fc0-95952035eb8c.png)
![image](https://user-images.githubusercontent.com/178406/148663934-1c7bcdc4-2a29-4da1-9e6d-909769f2b5ef.png)
![image](https://user-images.githubusercontent.com/178406/148663980-8ea0e5fc-2893-4dca-8cc7-5679db6de794.png)

I have the setting turned on that I believe should apply the Dead text and colors when a creature has the Condition: Dead
I then gave a creature the Dead condition.  Then I gave them 0 HP and the Dead Condition.
Still the Health Estimate list the Creature as Unconscious.

The macro works fine.
I tried Dead and dead as the attribute, just to make sure.

Foundry Stable 9.242
PF2e System 3.1.3.9639
HealthEstimate: 2.6.19

**Comment by galaara98** [comment]
i checked and the icons/svg/skull.svg is the death marker

**Comment by mclemente** [comment]
Yes, it's not working for PF2e, The skull isn't an effect like in other systems, I'll talk to the PF2e devs to find out a solution.

**Comment by mclemente** [comment]
Should be working now.

**Comment by galaara98** [comment]
Yup, all fixed

Thank you so much for your work... i super enjoy your mod
