### ISSUE TITLE
You cannot register a Keybinding after the init hook

### ISSUE THREAD

**Issue by Lazytron** [mclemente/healthEstimate#57]
![image](https://user-images.githubusercontent.com/32400728/149839161-4255d0a2-d211-4ec6-a5a5-dae2f197fa79.png)

**Comment by mclemente** [comment]
That's odd, it is [inside the init](https://github.com/mclemente/healthEstimate/blob/master/healthEstimate.js#L14) and other people that host on Forge would've ran into that issue way before you.

Are you running the Keybind Lib module on a V9 world? If you do, that might be it. Try reinstalling if don't, even though I doubt that would change anything. If neither work, I'll try checking with the Forge devs.

**Comment by MorganVergara** [comment]
I am also seeing this, with the same error. The full stack trace is here:

![image](https://user-images.githubusercontent.com/30846057/150241635-6247920a-cbd5-4967-ba65-bdfe4b2e5668.png)

I'm not running Keybind Lib either.

Thanks

**Comment by mclemente** [comment]
@MorganVergara are you hosting on Forge too? I'm trying to pinpoint the source of the issue.

It's really odd, since the 6th line (`initialize @ foundry.js:5403`) is exactly the call to the "init" hook.

**Comment by MorganVergara** [comment]
Yes, I am. I haven't tried it locally, but it does happen on Forge. Seems to work ok regardless, but the error is logged.

**Comment by mclemente** [comment]
So the keybindings are shown in the Controls window as normal? Or that's the only part of the module not working?

**Comment by Doresain** [comment]
Getting the same error - also hosted on The Forge. 

Yes, keybindings ARE shown in the Controls window.

![image](https://user-images.githubusercontent.com/26096062/150299658-96b0a71d-d910-49e5-bcc0-d21e15c5116b.png)

**Comment by Sasmira** [comment]
Hello Hello, 

I have this error too but I'm using a VPS on OVH 
<img src="https://puu.sh/IEfLI/0a8842719f.png">

S.

**Comment by mclemente** [comment]
I've also ran into this error while self-hosting, so it isn't specific to any type of hosting, but I'm still clueless about what causes it.
