### ISSUE TITLE
"Hit Points Attribute" not working

### ISSUE THREAD

**Issue by theMagius0** [mclemente/healthEstimate#59]
**Foundry Version**: 9.242
**Game System**: Fallout 2d20 9.0.0
**Health Estimate Version**: 2.6.22
**Browser**: Firefox 96.0.1

The Fallout Game System uses "health" instead of "hp" for determining hit points in fallout-main\lang\en.json as follows:

> "FALLOUT.HEALTH": {
>     "health": "Health",
>     "max": "Max Health",
>     "current": "Current Health"
>   }

So, in "Hit Points Attribute" of  Health Estimate Game Settings, I typed in:

> health

And I'm receiving this error in F12 debug:

> Health Estimate | Error on HealthEstimate._getEstimation(). Token Name:  Trader / Caravan Merchant . Type:  npc TypeError: hp is undefined
>     fraction generic.js:10
>     getFraction logic.js:87
>     _getEstimation logic.js:289
>     _handleOverlay logic.js:280
>     initHooks logic.js:253
>     _call foundry.js:294
>     callAll foundry.js:253
>     _onHoverIn foundry.js:21708
>     _onHoverIn foundry.js:38715
>     callback foundry.js:24060
>     _handleMouseOver foundry.js:24177
>     emit index.js:181
>     dispatchEvent interaction.min.js:8
>     processInteractive interaction.min.js:8
>     onPointerMove interaction.min.js:8
>     addEvents interaction.min.js:8
>     setTargetElement interaction.min.js:8
>     r interaction.min.js:8
>     initPlugins core.min.js:8
>     r core.min.js:8
>     create core.min.js:8
>     po core.min.js:8
>     t app.min.js:8
>     initialize foundry.js:19691
>     initializeCanvas foundry.js:5656
>     setupGame foundry.js:5528
>     _initializeGameView foundry.js:6479
>     _initializeView foundry.js:6455
>     initialize foundry.js:5415
>     call_wrapped libWrapper-wrapper.js:510
>     libWrapperInit libWrapper-api.js:776
>     initialize#0 libWrapper-wrapper.js:186
>     <anonymous> foundry.js:62282
>     async* foundry.js:62264

Correct me if I'm wrong here, but...

Shouldn't the field marked "Hit Points Attribute" attempt to replace the undefined "hp" in the debug with "health"?

Is there something I'm missing?

**Comment by mclemente** [comment]
It's the data path, not the name. Use `actor.data.data.health`.

**Comment by theMagius0** [comment]
McLemente,

Appreciate the assist.

Didn’t realize it was the entire path.

Tested and working.

Thx,
