### ISSUE TITLE
Not working in latest update

### ISSUE THREAD

**Issue by aboleba** [mclemente/healthEstimate#60]
Estimates no longer showing up.

Disabled all other modules, still not showing up.

**Comment by monkey-bars** [comment]
Running PF2e, also having the same issue.

**Comment by aboleba** [comment]
I'm on 5e.

Latest update fixed it for me.

**Comment by monkey-bars** [comment]
> @monkey-bars any errors on the console?

Three:
TypeError: Error thrown in hooked function '' for hook 'setup': (intermediate value)(...).join is not a function
[Detected 2 packages: healthEstimate, lib-wrapper] **foundry.js:316:28**

Uncaught (in promise) TypeError: (intermediate value)(...).join is not a function
[Detected 2 packages: healthEstimate, lib-wrapper] **pf2e.js:38:52**

Error: Error thrown in hooked function '' for hook 'canvasReady': This is not a registered game setting
[Detected 3 packages: healthEstimate, lib-wrapper, perfect-vision] **foundry.js:316:28**

**Comment by mclemente** [comment]
It's the same issue, reinstall the module and it should be fixed.
