### ISSUE TITLE
Skull image not showing over dead monsters

### ISSUE THREAD

**Issue by KoodGarma** [mclemente/healthEstimate#69]
Need help where skull image is not showing over dead monster token < 0 HPs. Anyone else come across this and fixed it? Thx in advance!

**Comment by mclemente** [comment]
This module doesn't apply the marker automatically. The related settings are meant for games that use an icon other than the default skull.

**Comment by KoodGarma** [comment]
> This module doesn't apply the marker automatically. The related settings are meant for games that use an icon other than the default skull.

Thanks sorry just making sure I understand correctly, is there a way to add an image?
