### ISSUE TITLE
Death Marker icon not visible

### ISSUE THREAD

**Issue by DesktopMan** [mclemente/healthEstimate#7]
Foundry version: 0.7.9
Module version: 2.5.1.3

I'm using the default Death marker _icons/svg/skull.png_. The image URL is correct because the "Death State on Condition" is working, however the icon is not added to the token when a token is marked as dead.

**Comment by mclemente** [comment]
This module doesn't add the skull automatically. See https://github.com/mclemente/healthEstimate/issues/5#issuecomment-817048180.
