### ISSUE TITLE
No interface to configure the health path

### ISSUE THREAD

**Issue by r-valyar** [mclemente/healthEstimate#71]
It is not clear how to configure this module to display health estimation based on system's health mechanics. I am trying to make it work for Symbaroum but to no avail. 

I have Conan 2d20, Pathfinder 2 and Twilight 2000 and it works fine, unfortunately I don't see how to make it work for Symbaroum. 

Any pointers?

**Comment by mclemente** [comment]
You need to find out the data path for health on the system, it's easier if you ask around on the #free-league chat on Foundry server since I don't play Symbaroum. It's probably `health.health.toughness`, but I'm not sure.

**Comment by r-valyar** [comment]
I know the data path, but I fail to see where I provide this data to the module.

**Comment by mclemente** [comment]
![image](https://user-images.githubusercontent.com/5288872/164586136-0239d3e4-6890-44db-a083-cf2078641a67.png)

**Comment by r-valyar** [comment]
There is no such entry:

![image](https://user-images.githubusercontent.com/63558984/164617944-4f281d4c-c42b-47fd-a702-60beb8f14157.png)

**Comment by mclemente** [comment]
It will be fixed on the next release.
