### ISSUE TITLE
Feature Request: Only show estimation to players

### ISSUE THREAD

**Issue by roi007leaf** [mclemente/healthEstimate#77]
The way i play my game is with HP bar on enemies so ill know the exact values of the monsters, and my players with HE module.
is there a way to make the GM not see the estimation? so i use the hp bar on the monsters and the players will see the estimation?

**Comment by mclemente** [comment]
Hi, sorry for the delay on answering, I've been busy. You can do that by changing the `Show Estimates: Users` to Players.
