### ISSUE TITLE
Doesn't work on The witcher TTRPG

### ISSUE THREAD

**Issue by DKtric3L** [mclemente/healthEstimate#79]
In this system hp attribute is derivedstats.hp, after filling it, nothing happened.

**Comment by mclemente** [comment]
Try `actor.data.data.derivedStats.hp`.

**Comment by DKtric3L** [comment]
> Try `actor.data.data.derivedStats.hp`.

Nope, unfortunatelly.
There is all attributes related to HP. (ScreenShot 1) 
Also i have combat tracker group and it's working fine with HP tracking, but its attribute don't work with your addon...(SS2)
And there is attributes in token settings(SS3)

![1](https://user-images.githubusercontent.com/105752167/172491350-4ce41537-5a59-4307-9bb1-d92904275a59.png)
![2](https://user-images.githubusercontent.com/105752167/172491353-4bb7aae6-2450-4d38-8ab5-6500be58e007.png)
![3](https://user-images.githubusercontent.com/105752167/172491354-13f370bf-aabd-4d9a-8dff-bf2f97254353.png)

**Comment by DKtric3L** [comment]
I don't really understand the code, but I think it could somehow tell you how to solve the problem. I also tried this attribute, all in vain.
![изображение](https://user-images.githubusercontent.com/105752167/172492503-b0c55113-a3b6-408e-8a7d-bd8bf634ced8.png)

**Comment by DKtric3L** [comment]
Ok i found the method to detect right stat, but this still not work. What am i doing wrong?
![изображение](https://user-images.githubusercontent.com/105752167/173522284-56fd565b-7b54-4ba1-986f-f18eebc91b3b.png)

**Comment by DKtric3L** [comment]
found the issue - Temporary hp parameter, disabled it and it works. Thank you!
![изображение](https://user-images.githubusercontent.com/105752167/173542141-ed0c955d-c7a6-4da2-aa6b-fd068f47177b.png)
