### ISSUE TITLE
[Feature Request] Always show health estimative

### ISSUE THREAD

**Issue by patrickporto** [mclemente/healthEstimate#81]
Is possible to add an option to always show the health estimative without the need to mouse hover?

**Comment by mclemente** [comment]
It isn't  possible, the Estimate inherits from `BasePlaceableHUD`, which is the same as the buttons that show up when you right click a token, so it can't be rendered more than once.

**Comment by patrickporto** [comment]
I can force show with custom css but The estimative is not update. I want to show health estimative on in-person session so always show the estimative is the better way to me

**Comment by mclemente** [comment]
This will be added on the next version for Foundry V10.
