### ISSUE TITLE
Name shown in chat notifications even if hide names is checked

### ISSUE THREAD

**Issue by IrmatDen** [mclemente/healthEstimate#85]
Hello,

I've check the "hide names" option in health estimate tokens' options, and the token names still appear in chat. After checking out the source code, it seems to me that in logic.js@outputStageChange, you only replace the actor's name IIF the token's "display name" option is set to "Never displayed".
As a GM, I like the names to be displayed, always or hovered, for a lot of token ; in addition to named NPCs, I'm using Token Mold to generate adjective to try to generate a small detail on the fly. Due to that, my players got a good laught out of a "Fulfilled Zombie" :)
I did too, not gonna lie, but I'm worried now that it might spoil some names.

Since I think the fix for this is transforming the condition to be `|| actor.data.displayName == 0`, it's a breaking change from the historic behavior. Thus I'm reluctant to create a PR for this. I'm also reluctant to create a PR adding another "Hide names" option, it seems redundant.

What's your thought on that please? Is it better to change the actual implementation or to create another option? Or a better third option maybe?

Note: I'm using Foundry V9, and Health Estimate is fully updated on this version.

**Comment by mclemente** [comment]
There's two keybinding controls (`Hide Names` and `hideHealthEstimate`) for hiding the names, but I reckon that the feature could should better and assumes people run the game the same way I do.

It also made me notice players' tokens with the Never Displayed option will be obfuscated because of that logic.

I'm thinking about checking for `actor.data.displayName <= 20` (when selected/hovered by owner) and also check for `!token.actor.hasPlayerOwner` so you'd be able to use whatever private option and also not obfuscate players' tokens.

**Comment by IrmatDen** [comment]
> There's two keybinding controls (`Hide Names` and `hideHealthEstimate`) for hiding the names, but I reckon that the feature could should better and assumes people run the game the same way I do.

Oh, it didn't cross my mind to check keybindings. I don't really use them, but when hidden with this method it behaves exactly like I want: name always displayed on canvas, and names in notification only visible to me and not the players 👍 

> I'm thinking about checking for `actor.data.displayName <= 20` (when selected/hovered by owner) and also check for `!actor.actor.hasPlayerOwner` (ignore the double actor, the first one is actually a `token` object) so you'd be able to use whatever private option and also not obfuscate players' tokens.

Would you consider adding this condition too `displayName == 40 /* always for owner */ && !actor.actor.hasPlayerOwner` please? I like having all my tokens' names visible, either due to Token Mold prefixes, or simply to have an npc's name right under my eyes.
If it makes it incompatible with another feature, I understand, and I'll use the keybindings instead.

**Comment by mclemente** [comment]
Closing this as it is in the future V10 release.
