### ISSUE TITLE
Unset dead flag if death marker icon condition is removed

### ISSUE THREAD

**Issue by SalieriC** [mclemente/healthEstimate#86]
I'm not entirely sure whether I'm the oddity here or if this is a problem others experience as well. 
When using the mark dead macro, a flag is set that marks the token as dead. Trouble is, that this can only be removed in script. So if there is a script that removes the condition with the dead marker as its icon, the estimation keeps to be the death state. This is also true if the condition is manually removed. This is a problem with hasty players or when other modules remove the condition.

This could be fixed by unsetting the flag in the `deleteActiveEffect` hook after checking if the deleted AE has the death marker as its icon. Unfortunately, I don't see a way to access the token in that hook as the AE only seems to carry the actor. This could still be done by checking the users viewed scene for tokens with the `parent` of the removed AE. This leaves room for some amount of error ofc but would probably work in most cases. Or maybe there is a smarter solution.

**Comment by mclemente** [comment]
You can just run the macro again to unset the flag (technically, set it to `false`, which is effectively the same thing for the logic).

Also, why are you even using the macro if you're using the marker? They don't depend on each other and achieve the same thing.

What do you mean by "hasty players"? Players aren't meant to use the macro.

**Comment by SalieriC** [comment]
> What do you mean by "hasty players"? Players aren't meant to use the macro.

Exactly. It is not intended for players, so players might just remove their condition, expecting to not be marked as dead anymore which obviously fails if the flag is set.

> Also, why are you even using the macro if you're using the marker? They don't depend on each other and achieve the same thing.

I use it for functions in my module. Some users don't set HE up as expected so the flags come in handy but are kinda prone to the above error.

**Comment by mclemente** [comment]
>It is not intended for players, so players might just remove their condition, expecting to not be marked as dead anymore which obviously fails if the flag is set.

How are players removing the condition? They can't change conditions or toggle the Mark Defeat button on the Encounter Tracker.
Also, why are players being marked as Dead often if they're coming back to life during the same encounter often? Why not just change the last stage to "Dying" (instead of Unconscious") and use the module as normal?

>Some users don't set HE up as expected

If the death marker is different than the default skull, just set up a hook on `ready` that checks `game.settings.get("healthEstimate", "core.deathMarker")` and set it to the correct path instead.

Also, if you want to affect tokens when `deleteActiveEffect` is called, just use this:

```js
Hooks.on("deleteActiveEffect", (activeEffect, options, userId) => {
	let tokens = canvas.tokens.placeables.filter((e) => e.actor && e.actor.id == activeEffect.parent.id);
	for (let token of tokens) {
		if (token.document.flags?.healthEstimate?.dead) token.document.unsetFlag("healthEstimate", "dead");
	}
});
```

**Comment by SalieriC** [comment]
> How are players removing the condition? They can't change conditions or toggle the Mark Defeat button on the Encounter Tracker.

It's a Savage Worlds thing.

> Also, why are players being marked as Dead often if they're coming back to life during the same encounter often? Why not just change the last stage to "Dying" (instead of Unconscious") and use the module as normal?

It's also a Savage Worlds thing. I could get lost into the details if you wish, but the gist of it is: Savage Worlds is - from other systems point of view - just weird in many regards and is often difficult to understand for non-Savages.

> Also, if you want to affect tokens when deleteActiveEffect is called, just use this:

Something like it was what I was suggesting. Just check if the deleted AE has the death marker icon path. I think it is better suited in HE itself than randomly appearing in other modules. Also I think it is a real improvement. But in the end, you will be the judge of that.
