### ISSUE TITLE
Star Wars FFG `Error on HealthEstimate._getEstimation()` when use vehicle threshold is unchecked

### ISSUE THREAD

**Issue by Carl-Hugo** [mclemente/healthEstimate#90]
I'm using version 28.0 of Health Estimate.
When mousing over a vehicle, using the Star Wars FFG game system, and the *use vehicle threshold* is unchecked in the settings, the following error is written to the console: 

![image](https://user-images.githubusercontent.com/5885505/186552335-179e0a85-85eb-4f07-94d1-0505d94f795b.png)

Your code:

```javascript
const fraction = function (token) {
	let hp = token.actor.data.data.stats.wounds;
	if (token.actor.data.type === "vehicle" && game.settings.get("healthEstimate", "starfinder.useThreshold")) {
		hp = token.actor.data.data.stats.hullTrauma;
	}
	return Math.min((hp.max - hp.value) / hp.max, 1);
};
```

After digging a bit using the debugger, I found that `hp` is `undefined` because `token.actor.data.data.stats.wounds` is `undefined` because the token is a vehicle and since `useThreshold` is `false` then the `hp = token.actor.data.data.stats.hullTrauma;` logic is never executed. That function then returns to its caller, leading to the error.

![image](https://user-images.githubusercontent.com/5885505/186554136-41a049b7-e357-41e0-93ff-8aa362d1b6ca.png)

I'm not sure about the role of the `useThreshold` setting here, but if it is unnecessary, you could remove it, and the error would be gone; like this:

```javascript
const fraction = function (token) {
	let hp = token.actor.data.data.stats.wounds;
	if (token.actor.data.type === "vehicle") {
		hp = token.actor.data.data.stats.hullTrauma;
	}
	return Math.min((hp.max - hp.value) / hp.max, 1);
};
```

If `useThreshold` must be kept, I suggest the code returns the `hullTrauma` in case `hp` is `undefined`, like this:

```javascript
const fraction = function (token) {
	let hp = token.actor.data.data.stats.wounds;
	if (token.actor.data.type === "vehicle") {
		const useThreshold = game.settings.get("healthEstimate", "starfinder.useThreshold");
		const hasHullTraumaStat = token.actor.data.data.stats.hullTrauma !== undefined;
		const hpIsUndefined = hp === undefined;
		if ((useThreshold || hpIsUndefined) && hasHullTraumaStat) {
		    hp = token.actor.data.data.stats.hullTrauma;
		}
	}	
	return Math.min((hp.max - hp.value) / hp.max, 1);
};
```

I do not mind opening a PR; just let me know what you think. 
Thanks

**Comment by mclemente** [comment]
That's a copy-paste mistake. `useThreshold` is meant to return 1, 0.5 or 0 based on the hp thresholds on other systems (e.g. 5e and pf2e). It is indeed useless for SWFFG.

**Comment by Carl-Hugo** [comment]
> That's a copy-paste mistake. `useThreshold` is meant to return 1, 0.5 or 0 based on the hp thresholds on other systems (e.g. 5e and pf2e). It is indeed useless for SWFFG.

Awesome, thank you! Any ETA on when you plan to release the fix?

**Comment by mclemente** [comment]
Oops, I commited to the V10 branch and there's still about a week before V10 Stable. A new release for V9 should be out now.

**Comment by Carl-Hugo** [comment]
Thanks a lot! BTW, I could have waited a week 🍻

**Comment by Carl-Hugo** [comment]
I found a few issues with 28.1 @mclemente.

By deleting the registration of the `starfinder.useThreshold` setting, the following line throws an exception:

![image](https://user-images.githubusercontent.com/5885505/187013240-295f164c-b638-464c-91a6-79e1a6907e3c.png)

The origin of the exception is from the following `foundry.js` code:

![image](https://user-images.githubusercontent.com/5885505/187013258-82af8aa2-1689-417d-92b3-1cfb9fb6bd57.png)

Adding the following during the initialization seems to work:

```javascript
game.settings.register("healthEstimate", "starfinder.useThreshold", {
    type: Boolean,
    default: false,
})
```

I assume that adding the setting back in `starwarsffg.js` would also work.

---

Moreover, changing `data.data` to `system` in your patch makes the module unusable (in v9 at least):

![image](https://user-images.githubusercontent.com/5885505/187013467-15caeef7-0450-4772-8765-001797e85438.png)

**Comment by mclemente** [comment]
Yeah, I should've waited for V10. I missed the V10 changes to the file and forgot I changed the utils.js file too. I'll revert the changes and wait until the 30th to release it for V10. I'm really sorry about that.

**Comment by Carl-Hugo** [comment]
No worries, I can wait for v10 no problem 🍻
