### ISSUE TITLE
Uncompatible with Foundry version 10

### ISSUE THREAD

**Issue by PrincessWires** [mclemente/healthEstimate#94]
According to the error: Metadata validation failed for module "healthEstimate": The file "lib/color-picker.min.js" included by module healthEstimate does not exist.

Hope this helps!

**Comment by mclemente** [comment]
Have you tried updating Health Estimate after you upgraded to V10? I fixed that issue at the start of the V10 Prototype https://github.com/mclemente/healthEstimate/commit/899109758e6b97b896b890f8743555fcc37bf2a3

**Comment by PrincessWires** [comment]
Unfortunately Health Estimate isn't even available in my list of modules. And reinstalling always brings be back to that error.

**Comment by PrincessWires** [comment]
Everything is working fine now, thanks for your help!
