### ISSUE TITLE
Estimate is spaced too high above tokens with a size greater than 1x1 tile

### ISSUE THREAD

**Issue by RuebenMF** [mclemente/healthEstimate#96]
Foundry 10.285
Warhammer Fantasy Roleplay 4th Edition 6.1.2
Tested using 'find the culprit' with only Health Estimate enabled

For tokens larger than 1x1 grid space, the estimate text is hovering above the token.

3x3 example:

![image](https://user-images.githubusercontent.com/77801645/190206084-21af08a5-f7c0-4b8a-af5e-b249588a99c4.png)

2x2 example:
![image](https://user-images.githubusercontent.com/77801645/190206491-84b83896-d0ce-436b-aa18-4beefe36d511.png)

1x1 example (unaffected):

![image](https://user-images.githubusercontent.com/77801645/190206230-0bbf1baa-5838-48b9-9655-5a82f157006f.png)

Let me know if there's any additional information I can provide :)

**Comment by mclemente** [comment]
I could've sworn I pushed that change already, it was on the test for zoom scale (https://github.com/mclemente/healthEstimate/issues/87#issuecomment-1236024418). Sorry, it'll be fixed on a later release.

**Comment by RuebenMF** [comment]
Thanks :)

**Comment by Zamrod** [comment]
> I could've sworn I pushed that change already, it was on the test for zoom scale ([#87 (comment)](https://github.com/mclemente/healthEstimate/issues/87#issuecomment-1236024418)). Sorry, it'll be fixed on a later release.

With the test for zoom scale enabled, if you have the labels set to bottom, they don't appear at the bottom of larger tokens:

![image](https://user-images.githubusercontent.com/12570777/190541149-6500e066-e4a3-49d7-9516-eac99b230961.png)
